### ISSUE TITLE
Socketstream cannot connect because connect.session is not executed during handshake

### ISSUE THREAD

**Issue by nponeccop** [socketstream/socketstream#219]
In many scenarios the only HTTP request a user performs is socket.io handshake request. As connect.session middleware is not used during this request, session id becomes missing or corrupt, and socketstream cannot connect or reconnect.

## Scenario 1

User's institution uses Squid proxy to cache pages. Two users visit a website one after another. The second user gets all static resources from cache so when the socket.io handshake is performed, the session cookie is not present and socketstream connection fails.

## Scenario 1a

Same as Scenario 1, but the website uses a reverse proxy.

## Scenario 1b

The reverse proxy from scenario 1a strips Set-Cookie headers from all cacheable content. As socketstream is designed so ALL content is cacheable, the only place a user can get session cookie is socket.io handshake request. But as connect.session is not engaged during handshake, the browser doesn't have a chance to receive a cookie, and socketstream connections fail.

## Scenario 2

A user keeps a page open for a long time, so session cookie expires. Then user's loses connectivity for some time. When connectivity is restored, socketstream tries to reconnect. As session id is missing during handshake and no other HTTP requests are performed during reconnection, connection fails.

## Scenario 3

Web server is upgraded while a user keeps a page open. When server is shut down, the user loses connection and when server is brought back the same problems as in Scenario 2 appear. In addition, the session may become invalid because cookie name, format or signature was changed during upgrade.

---------------------------

As for solution to this problem, I'm thinking of inserting `cookieParser` and `session` middleware before socket.io instead of after.

While socket.io doesn't have direct support for decoration with connect-style middleware, we can use the same approach as socket.io itself. Here are the relevant fragments from manager.js of socket.io:

```Javascript
  // reset listeners
  this.oldListeners = server.listeners('request');
  server.removeAllListeners('request');

  server.on('request', function (req, res) {
    self.handleRequest(req, res);
  });
...

    for (var i = 0, l = this.oldListeners.length; i < l; i++) {
      this.oldListeners[i].call(this.server, req, res);
    }
```

**Comment by paulbjensen** [comment]
I'm going to close this, and if it crops up again, I'll pick it up.
