### ISSUE TITLE
Document installing and using npm modules in client dir

### ISSUE THREAD

**Issue by pygy** [socketstream/socketstream#287]
This is a very handy feature of browserify that SS does not support at the moment.

I tried to make a node_modules symlink to the system directory. The libs install as expected, but the direcoty hierarchy is flatened and all .js files are provided as-is. For example, if you install node-uuid, `require("node-uuid")` fails, but `require("uuid.js")` does. I also get a slew of errors 500 for non-js files included in the node-uuid directory.

This isn't a problem for the uuid module, since it is comprised of just one file, but more complex modules, or modules relying on other npm modules won't work at all.

There are a lot of pure JS npm packages that can be useful client side too...

**Comment by paulbjensen** [comment]
I think that this is definitely worth doing, and will therefore suggest it goes into 0.4

**Comment by arxpoetica** [comment]
Referencing ticket #465 as there are overlapping considerations.

**Comment by kulicuu** [comment]
I want to work on this feature and the whole client bundling module devvs, after doing the _connect_ stuff, which I'm working on this week.

**Comment by paulbjensen** [comment]
@kulicuu cool, please do. Thanks.

**Comment by thepian** [comment]
I'm adding a minor modification as part of #465 which allows referencing any code relative to the client folder. That takes care of bower if you include it in client. Not sure about npm if node_modules remain in the project root.

**Comment by thepian** [comment]
You can now do that with what is in the `next` branch. We just need an example/documentation.

**Comment by thepian** [comment]
@kulicuu If you want to work on this you should pick up #455 

It would be really neat, but I think it could easily be left for past 0.4, perhaps 0.4.2, assuming 0.4.1 are fixes based on feedback
