### ISSUE TITLE
Better support for data-bound server-rendered views and/or templates

### ISSUE THREAD

**Issue by drauschenbach** [socketstream/socketstream#289]
Client template support in SS is outstanding. But now I'd like to take it to the next level, and bake some data into the view on the server, before it's compiled. I can't find any documentation on this. Is Express required? I'd want to bind values to my main view, or maybe any template, using the ${varName} Jade syntax, since my main app view is a Jade template. Things that would be read out of the package.json file via the read-package-json module, like app name and version, come to mind. Maybe even a session key.

In a client definition, it might be nice to define values alongside the view, so that they can be passed into the Jade compiler:
````coffeescript
ss.client.define 'main',
  view:
    name: 'index.jade',
    options:
      appName: 'myapp'
      appVers: 'myappvers'
    css: ...
````

And as for rendering parts of Jade templates on the server during compilation, ss-clientjade, as an example, has a process() function that doesn't support passing my own options into the Jade compiler.

I believe the ss.client.templateEngine.use function would also need to be extended:
````coffeescript
serverOptions =
  appName: 'myapp'
  appVersion: 'myappvers'
ss.client.templateEngine.use 'ember', serverOptions
````

Or maybe there is a way to do all this today already?

**Comment by paulbjensen** [comment]
Marking as closed unless anyone objects.
