### ISSUE TITLE
Pack Client Assets doesn't import css files

### ISSUE THREAD

**Issue by hackable** [socketstream/socketstream#312]
I've noticed pack client assets doesn't import css files  for example if i had

@import 'libs/style.css'
@import 'libs/custom.css'
@import 'libs/font-awesome/font-awesome.css'

it doesn't import t

**Comment by paulbjensen** [comment]
Adding this into 0.3.12

**Comment by thepian** [comment]
I think it is important to ensure that you can still explicitly have @import statements in the compiled CSS if that is what you really want to do.

LESS and SASS formatters make the distinction, so it's important that this is a formatter responsibility not one in the bundler.

The simplest solution is to have a CSS Import Combining formatter.

**Comment by thepian** [comment]
The relative URL of assets now work the same in development and production in version 0.4

If you want to resolve @import statements in CSS you can make a custom bundler that does it for you.

So to me this is fixed.
