### ISSUE TITLE
RPC testing - ss.rpc not being loaded despite ss.start() call

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#332]
I've encountered an issue when trying to rearchitect Dashku for an upcoming feature. It appears that ss.rpc is not being loaded by ss.start().

I've tried to replicate the issue in a vanilla socketstream app, and the same thing happened.

To see this issue affecting Dashku, checkout the pluginArchitecture branch of https://github.com/anephenix/dashku, then run:

```
cake test
```

To see this issue affecting the vanilla socketstream app, checkout master on https://github.com/paulbjensen/ss-rpc-test-issue, and run:

```
cake test
```

It's worth noting that the master branch of Dashku is able to run cake test fine.

**Comment by arxpoetica** [comment]
I've been testing via Mocha and can't get `.rpc` to load either (it's just `undefined`).

I'm not 100% sure what you did here from your description. What do you mean by "use a plugin architecture"? How did you get the `.rpc` to show up?

**Comment by paulbjensen** [comment]
I think you have to call it via <code>ss.api.rpc</code>

**Comment by arxpoetica** [comment]
so...`require('socketstream').api` is defined, but not `require('socketstream').api.rpc`...?

What were you referring to above about plugin architecture?

**Comment by arxpoetica** [comment]
Just a little more info, I'm looking at what you did here: https://github.com/dashku/dashku/blob/master/test/server/rpc/widgetTemplate.test.js#L40

This test is passing?
