### ISSUE TITLE
Stub console.* calls for IE compatibility

### ISSUE THREAD

**Issue by plievone** [socketstream/socketstream#344]
I pulled the current master and packed the demo app assets, then grepped for some usual suspects in IE compatibility. There are (perhaps from browserify, so in all socketstream builds) some calls to console.error, console.trace and console.log. Perhaps one should make them empty functions if they are not defined (and with a typeof check as IE can break when coercing native functions to booleans)
```js
if (typeof console == 'undefined') console = {};
if (typeof console.log == 'undefined') console.log = function() {};
if (typeof console.error == 'undefined') console.error = function() {};
if (typeof console.trace == 'undefined') console.trace = function() {};
```

**Comment by thepian** [comment]
I don't think this is a Socketstream concern. There are libraries to take care of these, and many approaches. Stubbing, is unfortunately not an option.
