### ISSUE TITLE
Allow setting a global javascript object for the client (through the server)

### ISSUE THREAD

**Issue by mdedetrich** [socketstream/socketstream#353]
This is more of a feature request, however its something that is in (my opinion) required, at least for the work I do which involves using Facebook's javascript SDK on the client side

You should basically be able to set a javascript object (in JSON) format on the server, which is than accessible in browser clients

As an example, when you do something like this
```javascript
ss.client.define('main', {
    view: 'app.jade',
    css: ['common.styl'],
    code: ['system', 'libs/tinybox2.js', 'libs/jquery.js', 'libs/backbone.js', 'libs/facebook.js', 'app'],
    tmpl: '*',
    clientObject: {
        someVal: 1,
        anotherVal: "cheese"
    }
  });
```

Then in the browser you would be able to access this object (through something like ss.clientObject)

As mentioned earlier, this would be incredibly helpful for my case due to using facebook's javascript sdk, so it would look something like this (for my case)

```javascript
ss.client.define('main', {
    view: 'app.jade',
    css: ['common.styl'],
    code: ['system', 'libs/tinybox2.js', 'libs/jquery.js', 'libs/backbone.js', 'libs/facebook.js', 'app'],
    tmpl: '*',
    clientObject: {
        facebookAppID: config.get('facebookApplicationID')
    }
  });
```

And I would be able to access the facebookApplicationID through the client (and feed it into the SDK). I am sure there are other reasons to use something like this

Currently I have to manually change JS files (in this case the facebook.js) every time I deploy, and change it back when I work locally

**Comment by thepian** [comment]
We now have a branch with a solution

* view specific constants can be defined in the defintion. They will be global objects in the browser.
* global constants can be defined with ss.client.send('constant', 'name', 'value')

TODO: 
* documentation
* make constants available in formatters

@paulbjensen can you have a quick look if this seems Ok

**Comment by thepian** [comment]
@mdedetrich How does this match what you were doing?
