### ISSUE TITLE
how to force packing without running the server

### ISSUE THREAD

**Issue by luksch** [socketstream/socketstream#405]
I have a nice little deployment issues. I want to pack the assets in my grunt deployment script without starting the server for real. It seems that the packing only occurs when the server is really starting. So is there a way to avoid this?

Alternatively, it would be a workaround if I could at least stop the socketstream server from within the node app.

Thx all, socketstream is really terrific!

Lukas

**Comment by klausb** [comment]
I don't get it. The gist shows how to start the server from with npm, but does it help to stop the server, when the packing is done?

**Comment by thepian** [comment]
We should be able to provide an explicit way of packing resources without starting the server. Ideally I'd like to do it together with the Gulp shortcuts #473

**Comment by thepian** [comment]
I suggest we do this for 0.4 rather than 0.3

Could be done in tandem with Gulp integration/support

**Comment by thepian** [comment]
@paulbjensen It seems packing assets was a binary choice for all views rather than per client. Shouldn't that be a flag per client/bundler ?

**Comment by thepian** [comment]
This will be an experimental feature in 0.5 using Gulp underpinnings. You can do it with `ss.start('pack-all')`.

**Comment by thepian** [comment]
now in master
