### ISSUE TITLE
TASK: Project's files linting (jshinting)

### ISSUE THREAD

**Issue by RomanMinkin** [socketstream/socketstream#408]
Just decided to create a list of all the project's files need to be linted / reviews, so it could be easy to contributors to participate and do not overlap with each other.

@paulbjensen, could you please assign a milestone for this issue, some thing like **v0.3.11**

if anyone would like to help with code linting please feel free to join. Please post here the list of files you are going to work on and use ```grunt jshint:server```, ```grunt jshint:client``` or just ```grunt jshint``` to check you work as describe in [Guidelines for contributing](https://github.com/socketstream/socketstream/blob/master/CONTRIBUTING.md). 

It's important to use ```grunt jshint``` because ```grunt``` has project setup for linting. which is different for ```client``` and ```server``` code. 

it's bunch of linting errors right now, but we will fix them soon. I'll try to keep this list up to date:

- [x] lib/cli/generate.js
- [x] lib/cli/index.js
- [x] lib/client/asset.js
- [x] lib/client/formatters/css.js
- [x] lib/client/formatters/html.js
- [x] lib/client/formatters/javascript.js
- [x] lib/client/formatters.js
- [ ] lib/client/http.js
- [x] lib/client/index.js
- [ ] lib/client/live_reload.js
- [ ] lib/client/magic_path.js
- [x] lib/client/pack.js
- [x] lib/client/serve/dev.js
- [x] lib/client/serve/ondemand.js
- [x] lib/client/serve/utils.js
- [x] lib/client/system/index.js
- [x] lib/client/system/libs/browserify.js
- [x] lib/client/system/libs/json.min.js
- [x] lib/client/system/modules/eventemitter2.js
- [x] lib/client/system/modules/socketstream.js
- [x] lib/client/template_engine.js
- [ ] lib/client/template_engines/angular.js
- [x] lib/client/template_engines/default.js
- [x] lib/client/template_engines/ember.js
- [x] lib/client/view.js
- [x] lib/client/wrap.js
- [x] lib/http/index.js
- [x] lib/http/router.js
- [ ] lib/publish/index.js
- [ ] lib/publish/transport.js
- [ ] lib/publish/transports/internal.js
- [ ] lib/publish/transports/redis.js
- [ ] lib/request/index.js
- [ ] lib/request/middleware/index.js
- [ ] lib/request/middleware/internal.js
- [ ] lib/request/responders/events/client.js
- [ ] lib/request/responders/events/index.js
- [ ] lib/request/responders/rpc/client.js
- [ ] lib/request/responders/rpc/index.js
- [ ] lib/request/responders/rpc/request.js
- [ ] lib/session/channels.js
- [ ] lib/session/index.js
- [ ] lib/socketstream.js
- [x] lib/utils/file.js
- [x] lib/utils/misc.js
- [x] lib/utils/unique_set.js
- [ ] lib/websocket/event_dispatcher.js
- [ ] lib/websocket/index.js
- [ ] lib/websocket/subscriptions.js
- [ ] lib/websocket/transport.js
- [ ] lib/websocket/transports/engineio/client.dev.js
- [ ] lib/websocket/transports/engineio/client.js
- [ ] lib/websocket/transports/engineio/index.js
- [ ] lib/websocket/transports/engineio/wrapper.js

**Comment by thepian** [comment]
I don't see any `grunt hint`. Do I just install jshint globally and run it on the project?

**Comment by paulbjensen** [comment]
No, instead do <code>npm run lint</code>.

**Comment by thepian** [comment]
btw, be careful not to go overboard. As an example,

(_ref = options.packedAssets) !== undefined

vs 

(_ref = options.packedAssets) != null

Is not the same test. Quite often null and undefined values are synonymous, so `== null` is the correct test. `eqnull: true` should allow such a test.

**Comment by paulbjensen** [comment]
Yep, agreed. I've been trying to use <code>!condition</code> instead of <code>=== undefined</code> or <code>=== null</code> in these cases, was there a line I broke?

**Comment by thepian** [comment]
I just saw that as a linting refactoring, and I wanted to point out that the tests are not the same. I personally favour VAR != null, as it will accept anything other than null and undefined such as "" or 0.

In #465 I have relaxed the linting rules a bit as they seem very aggressive.

**Comment by thepian** [comment]
I'd suggest that we have two jshint files. One for lib and one for unit tests. This way we avoid linting fixtures and other auxiliary files. And we can adjust the rules to fit the purpose

**Comment by paulbjensen** [comment]
What if we add fixtures and auxiliary files to .jshintignore?

**Comment by thepian** [comment]
That might be a good idea, you might want to drop in quite nasty stuff for fixtures

**Comment by thepian** [comment]
@RomanMinkin what should we do with this story?

While I would love to have no linting issues a lot might be lost when merging with 0.4

Secondly the linting issues remaining are quite concentrated in `engingio`.

**Comment by thepian** [comment]
Now we have a commit hook to disallow jshint issues
