### ISSUE TITLE
Make client-side compilation inherit file extensions from client-side formatters

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#424]
Colter McQuay made a really good suggestion about letting client-side formatters pass their file extension to browserify, rather than having to define them in the lib/client/system/libs/browserify.js file.

I think that this is a good idea, so I will explore how it can be done, and if it works, then I will do it.

- [x] require should work loading a code module regardless of the source format(coffee/ES/JS)
- [x] allow explicit file path if used
- [x] test coverage of our browserify implementation
- [x] tutorial for using require in browser

**Comment by thepian** [comment]
Done
