### ISSUE TITLE
Connection issue around engine.io and Android app

### ISSUE THREAD

**Issue by mooglin** [socketstream/socketstream#426]
I'm need to pack my socketstream assets so they can stand alone. For example, pack the assets and just open the html file in your browser to find a fully working app that connects to the socketstream server and runs.

There are two main problems I've run into so far:
- Packing the assets in a way they can be referenced relatively instead of referencing the server's static dir. 
- Passing the server location to engine.io on the client side.

I may very well be missing others but I haven't solved these two yet.

Any feedback on how I could go about solving these problems would be great.

**Comment by kulicuu** [comment]
I can look into this anew with the new EngineIo configuration.  I don't understand everything about the use case and requirements for API.

**Comment by thepian** [comment]
@mooglin With the improvements in 0.4 you should be able to fix this.

Assets are in the same location during development and production.

You can pass constants to the client by adding them to the client definition.

Obtaining session id through a cookie would be a problem with local files. This should be addressed in 0.4.1 as the general focus.

Feel free to continue this request/discussion under 0.4.1
