### ISSUE TITLE
engine.io upgrade w/support for webworkers, compression, etc.

### ISSUE THREAD

**Issue by nhitchins** [socketstream/socketstream#435]
Has anyone successfully updated engine.io to the latest version (0.9 fixes various outstanding issues - namely better support for clients behind proxies)?

I noticed that polidore had updated engine.io (server) to version 0.7.9 with his PR: https://github.com/socketstream/socketstream/pull/397
-- However the engine.io-client is still using 0.3.10 
https://github.com/socketstream/socketstream/blob/master/lib/websocket/transports/engineio/client.js#L9

I've been messing around with 0.9 (engine.io + engine.io-client) but running into issues...looks like cookie is not being sent to server in request headers during polling/handshaking. thought it may be related to https://github.com/LearnBoost/engine.io/issues/197 however I can confirm its NOT sending XDomain requests (ie. appears to be a different problem).

**Comment by kulicuu** [comment]
Just started on this today:

- I'm working on bringing it to 1.4.3

- If okay, I'm going to use this thread as discussion and notes storage for this process.  If not okay, maybe I'll start another issue and/or run a wiki page devoted to the process -- it's involved and lots of design decisions are available.  I just noticed in the engine.io-client History.md that as of v8.2 engine.io on the client runs great on (web)workers.  Stuff like that is crucial.

https://github.com/Automattic/engine.io-client/blob/master/History.md

https://github.com/Automattic/engine.io/blob/master/History.md

**Comment by kulicuu** [comment]
As for OP (on subject of cookie sent in headers): in 1.4.3 there is a direct `sid` attribute on the `socket.transport` now.  Still getting errors or the client... a ways to go yet... but hopefully next few days can maybe get something working. I _do_ have time now.

**Comment by kulicuu** [comment]
Hilarious, I didn't realise until 5min ago that the client.js file(s) were of the engine.io-client.

I almost have this working already.  (i think... ;0 )

**Comment by kulicuu** [comment]
Wow, this is going extremely well.  Almost completely working.  I'm rewriting the wrapper.js file now.  Actually just hacking it together-- proper rewrite / refactor over next couple days.  Very excited to see this coming together so fast!

**Comment by paulbjensen** [comment]
Thanks @kulicuu, absolutely fine to document notes in the thread.

**Comment by arxpoetica** [comment]
Epic.

**Comment by nhitchins** [comment]
Yeah my apologies for not putting together a PR on the 0.9 upgrade. Really interested to see how you go with the 1.4.3 upgrade. The ultimate goal would be to get binary websockets working!

Incase you're still bug hunting, heres a snippit that you may want to look into (the processSession function in websocket/transports/index.js) https://gist.github.com/nhitchins/f2ef70a63331a29427aa#file-index-js

**Comment by kulicuu** [comment]
'@'everybody: _THANKS!_

#### @nhitchins :

- re bughunting:  the bughunt I was referring to there have to do with later commits on the master than where I pulled my branch from.  Basically, the other day I started doing SocketStream devvvs for the first time in a long while and started a new fork, and found -- much chagrin -- that the latest master commits fail to load and run my app successfully.  So the branch that I'm developing this _engine.io_ stuff on is branched off from a the commit of dec16 from the master branch.  Now, since I'm assuming that the later commits contain good work, there remains the issue of troubleshooting what troubles have creeped into them.   

- re binary websockets: first I've heard of it. (after reading a tiny bit about it) Sounds great!  It looks like _engine.io_ supports this, so of course I'll consider supporting it to be part of my job here.  At least to give it a good start.  

- other stuff:  As well as binary websockets, there are likely a lot of new features to leverage.  As I mentioned in a post above, the one that really caught my eye was that as of something like v8.0 _engine.io-client_ can be run in a web-worker.  I would assume that this would be a good way to go, but really my deep low-level browser knowledge is not so expert, so would love to hear opinions on this... but my impression is that this would offer developers substantial performance benefits.

**Comment by kulicuu** [comment]
Wish list on engine.io websocket binary API structure ?

**Comment by nhitchins** [comment]
@kulicuu 
- I've heavily modified my version of socketstream for a specific use-case so cant submit a PR against it. I'll grab the official release and do some testing when you're close to a final commit. Lets get that happening first. (any gotcha's you've come across with the upgrade so far?)

- Re: Binary websockets. I'll take a look into this sometime over the next week and report back. I'm pretty sure the engine.io client/server handles Buffer/ArrayBuffer messages with automatic base64 encoding for browsers/transports that don't support binary frames - TBC. Will need to review the SS transport components to figure out what may need to change if anything. I'd be leaning towards sending all messages as binary in preparation for automatic compression: https://github.com/Automattic/socket.io/issues/1148

- Re: Web workers. I'd be really interested to hear what improvements if any would be gained by wrapping the engine.io client in a web worker. my understanding is that websockets are non-blocking (apart from any processing logic that gets triggered when the data arrives)? Has anyone tried/tested or confirmed this?

**Comment by kulicuu** [comment]
@nhitchins 

- No gotchas yet, but there are a lot of changes and I'm taking my time with verifying edge cases and pulling all the elements together.  One of the things I'm doing today and next few days maybe is making sure  the debug mode will work.  That's changed a lot so it's something I'm looking into integration-wise.  That's just an example.  A bunch of little things like that.

- automatic compression sounds great.  doing everything in binary i'll hold off on this week-- but for sure will be thinking about implementation strategies.

- Web-workers :  Yeah me too-- interested to hear opinions on this.

**Comment by nhitchins** [comment]
Looks like support for compression has been added. https://github.com/Automattic/socket.io/issues/1148. I still havent had a chance to review this yet, but now that you've got engine.io up to date it should make it a whole lot easier!

**Comment by kulicuu** [comment]
A deep thinking about sessions persistence is the meditation of the week.  Prototyping a tokens-based approach one of the first tasks.

The new engine.io implementation websockets connection doesn't persist over server restarts _or_ browser reloads.

**Comment by kulicuu** [comment]
I have _engine.io_ v1.5.1 working with persistent sessions now (I had overlooked something obvious).
I'll have a pull request ready in within an hour (need to clean up the .gitignore file and commit).  Sorry about the false start, ...
Will need to test more, and am still definitely working on the deeper overhaul stuff across the board, but happy to know this has come together unexpectedly.

**Comment by kulicuu** [comment]
Ah cool I see the issue has been renamed with more elaborate specification.  ;]

**Comment by thepian** [comment]
So can this be closed or updated to reflect the current state ?

**Comment by kulicuu** [comment]
It's upgraded very well, but not yet leveraging all new possibilities.  This will require some design insight and decisions on your (plural) part.  I'm also full-time into a new job, so absent for a bit.

**Comment by thepian** [comment]
I have created a new story #524  for this, please do the planning there.
