### ISSUE TITLE
Url gets parsed wrong in development mode

### ISSUE THREAD

**Issue by Waxolunist** [socketstream/socketstream#438]
[EDIT: Being able to have relative references from CSS to assets work the same in dev and production is quite important]

I am using express together with socketstream. Besides that I am using bower for client dependency management.
I configured bower to download its contents into `/client/code/system`.

Bootstrap is also in system as bower dependency. I configured stylus to include the bootstrap css. Bootstrap loads its fonts (glyphicons) relative from the url `../fonts/fontfile`.

That means, that requests in development go to `/_serveDev/fonts/glyphicon.woff` and in production mode to `/assets/fonts/glyphicon.woff`.

In development however the original url gets parsed as follows:

```
originalUrl: '/_serveDev/fonts/glyphicons-halflings-regular.woff',
  _parsedUrl: 
   { protocol: null,
     slashes: null,
     auth: null,
     host: null,
     port: null,
     hostname: null,
     hash: null,
     search: '?glyphicons-halflings-regular.woff',
     query: 'glyphicons-halflings-regular.woff',
     pathname: '/_serveDev/fonts',
     path: '/_serveDev/fonts?glyphicons-halflings-regular.woff',
     href: '/_serveDev/fonts?glyphicons-halflings-regular.woff' },
```
You see that the file name gets changed to a parameter without value.

Whereas in production mode the same request is as follows:

```
originalUrl: '/assets/fonts/glyphicons-halflings-regular.woff',
  _parsedUrl: 
   { protocol: null,
     slashes: null,
     auth: null,
     host: null,
     port: null,
     hostname: null,
     hash: null,
     search: null,
     query: null,
     pathname: '/assets/fonts/glyphicons-halflings-regular.woff',
     path: '/assets/fonts/glyphicons-halflings-regular.woff',
     href: '/assets/fonts/glyphicons-halflings-regular.woff' },
```

So in order to serve this file I have written following middleware:

```
var app = express();
app.get(/^\/(?:_serveDev|assets)\/fonts(?:\/(.+))?/, function(req, res){
  var file = req.params[0] || Object.keys(req.query)[0];
  res.sendfile(bowerpath + 'bootstrap/dist/fonts/' + file);
});
```

It's not a big issue, but why do requests to `_serveDev` get parsed different, than those to `assets`?

**Comment by thepian** [comment]
This is now fixed in 0.4, which we hope to release in a month or so. If you want to try it out check out the `next` branch.
