### ISSUE TITLE
Internal Events Bus :: development ideas

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#453]
I keep noticing this intriguing bit in `socketstream.js`:

```
// Create internal Events bus
// Note: only used by the ss-console module for now. This idea will be expended upon in SocketStream 0.4
var events = exports.events = new EventEmitter2();

```

I'm looking for, and interested in re-opening/extending, the discussion(s) on how this "idea [could be should be] extended upon in SocketStream [v.XYZ]"

What are the thoughts here?  I'm very interested.

**Comment by paulbjensen** [comment]
This feels like something to consider for 0.4

**Comment by kulicuu** [comment]
Same as the other one, I'm starting to do stuff with this in prototype form-- maybe something this week for a kind of branch pr... i.e. maybe would like to do some pr to branch for some of these.
