### ISSUE TITLE
Allow setting JSESSIONID cookie to support load-balancers in popular PaaS systems

### ISSUE THREAD

**Issue by klausb** [socketstream/socketstream#454]
When working with Cloudfoundry compatible PaaS environments, in order to get sticky sessions, the application has to set the JSESSIONID or SESSIONID cookie. Socketstream needs an API to set those cookies.

**Comment by klausb** [comment]
Paul,

any news on this one?

/klaus

**Comment by thepian** [comment]
Do I understand this correctly in that the cookie `connect.sid` is the current session ID, and you would like a way to set that to JSESSIONID ?

**Comment by thepian** [comment]
@klausb I've created https://github.com/socketstream/socketstream/pull/523 which should fix your issue.
What do you think?

**Comment by thepian** [comment]
If it doesn't solve your issue please reopen, it will be part of 0.3.12
