### ISSUE TITLE
Allow bower and npm modules to be used in client definitions

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#455]
The client definition feature is nice, but requires a certain folder structure. In 0.4 this is somewhat alleviated with relative paths. This solves the original objective of this issue.

There should be a way for a default bundler to treat Bower components and npm modules as source. To avoid watching a large and possibly conflicting structure these should be kept in the client directory.

One possible solution is scanning for packages.json and bower.json in the client directory and adding them as aliases for modules to be used in client definitions.
- [x] Allow direct inclusion of resources in project path
- [ ] Support root being below node_modules
- [ ] Get list of module names in bower and npm
- [ ] Configuration of css/code source locations alternative to css/code directories
- [ ] Configuration of multiple system and lib directories
- [ ] Make talk about the benefits of library level bundling vs file level bundling like newer browserify.
- [ ] Document how to add a bower component using relative path
- [ ] Document how to add an npm component using relative path
- [ ] Document how to add a bower component using module require
- [ ] Document how to add an npm component using module require
- [ ] Support module require of bower
- [ ] Support module require of npm
- [ ] Unit test module require of bower
- [ ] Unit test module require of npm
- [ ] Let the bundler control the module require resolution
- [ ] Detect modules for templates in client definition and treat it as include all templates in module

**Comment by thepian** [comment]
The good thing about _serveDev is that we can just change the meaning of the URL, as it isn't deployed. Do you have any progress on this?

**Comment by paulbjensen** [comment]
Not yet sadly, but I think it should be a consideration for 0.4

**Comment by thepian** [comment]
I will soon have something to show on #465 that should solve the problem.

**Comment by thepian** [comment]
http://localhost:9001/#/tutorials/client_side_development

I've changed the _serveDev/code , css , worker to serve relative to /client rather than the asset specific directory. That would allow you to put bower components into /client/components and specify files directly. Client definitions starting with dot are treated as relative to /client, otherwise as normal.

Of course you can always require / import from bower components indirectly from the client view source.

What do you think?

**Comment by thepian** [comment]
@paulbjensen Could you have a look at the next branch and see how you like the option to use relative dependencies in client defs.

**Comment by paulbjensen** [comment]
I'll try and get a look into it tonight. Thanks for your work, I'm sorry I
haven't been as active recently.

Regards,

Paul Jensen

On 3 March 2015 at 17:50, Henrik Vendelbo <notifications@github.com> wrote:

> @paulbjensen <https://github.com/paulbjensen> Could you have a look at
> the next branch and see how you like the option to use relative
> dependencies in client defs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketstream/socketstream/issues/455#issuecomment-76996748>
> .
>



-- 
Paul Jensen
07914 171 345

**Comment by thepian** [comment]
bower listing: https://www.npmjs.com/package/main-bower-files

sourcePaths gets confused when root is below node_modules base.

Perhaps there should be a magic directory called `modules/` that is meant to mean location in bower or npm. 

Magic paths in project

* client - the actual client path
* server - the actual server path
* modules - look up modules in npm or bower

**Comment by paulbjensen** [comment]
Closing as no longer working on it.
