### ISSUE TITLE
Create a Roadmap for SocketStream

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#468]
We need to create a feature roadmap for SocketStream

**Comment by arxpoetica** [comment]
What time on the 4th? Might be hard for me to do...

**Comment by kulicuu** [comment]
(UTC) anytime 08:00 to 19:00

**Comment by arxpoetica** [comment]
The reason this is tricky is that I'm EST and I'm gone in the morning (which is prime time for you UKers). :+1: I can probably squeeze in an early AM Boston time (between 11:00 and 13:00 UTC), but after morning, I'm really only available from 18:30 UTC on.

(This should help in conversions http://www.worldtimebuddy.com/est-to-utc-converter.)

Sorry for my limited schedule. If this proves to be too difficult to go back and forth in this thread on times, we can always put together a doodle http://doodle.com/ and try and plan ahead based on that.

**Comment by paulbjensen** [comment]
Would 1100 UTC work for everyone?

**Comment by arxpoetica** [comment]
That works great for me. :+1:

**Comment by kulicuu** [comment]
Very cool !

**Comment by arxpoetica** [comment]
we can use https://appear.in/socketstream ... just "knock" (I locked it down). (Open to alternatives if people have preferences.)

**Comment by paulbjensen** [comment]
Seems cool, speak tomorrow.

**Comment by kulicuu** [comment]
very good.

**Comment by kulicuu** [comment]
I have a microphone but no camera. (‘venerable’ 2009 Thinkpad X61)— might
be an issue. wasn’t able to connect to their server just now.

i’m on Skype as well wylie.joshuacullick or same in Gmail/hangouts, or
whatever else. hopefully *Appear* will work though— I’ll try again later.
​

**Comment by paulbjensen** [comment]
You can add ?video=off to the url in order to disable video (screen sharing will still work).

**Comment by kulicuu** [comment]
ah cool!

**Comment by kulicuu** [comment]
worked thanks!

**Comment by thepian** [comment]
sure. Is this a hangout? I don't know where to join

**Comment by paulbjensen** [comment]
http://appear.in/socketstream

**Comment by kulicuu** [comment]
supposed to be here :

https://appear.in/socketstream

**Comment by paulbjensen** [comment]
Have you chaps been able to join?

**Comment by kulicuu** [comment]
knocked but no answer

**Comment by paulbjensen** [comment]
Try again.

**Comment by arxpoetica** [comment]
also go here: https://gitter.im/socketstream/socketstream

**Comment by arxpoetica** [comment]
@kulicuu

**Comment by paulbjensen** [comment]
Ok, we're going to try a google hangout, will send invites via email

**Comment by kulicuu** [comment]
cool

**Comment by thepian** [comment]
I don't think I can get it to work. The WiFi here is pretty spotty, so not really a surprise.

My main wish for a roadmap is to have a builder based on latest Browserify and/or WebStack.
Second wish would be creating a working demo based on Express 4.

**Comment by arxpoetica** [comment]
Hi Everyone, I'm closing this issue since we've created a more proactive process for meeting and going over roadmap. If you'd like to be on the roadmap contact list (for meeting times, notes, etc.) go ahead and leave a note here, and we'll figure out how to get contact info, etc.

**Comment by kulicuu** [comment]
Wylie: email: wylie.joshuacullick@gmail.com
*btw:i’m hoping to have a fresh devEnv setup going next week, and I should
share insights with you then.*
​

**Comment by paulbjensen** [comment]
@thepian Sorry you didn't get to be on the call, next time. As for your requests, the 1st wish is intended, but not easy to do (SS uses a modified early copy of Browserify, so this is going to be a bit tricky), and as for the 2nd wish, there is a plan to upgrade connect, which should allow using express 4 to happen.

**Comment by arxpoetica** [comment]
@kulicuu @thepian @paulbjensen you guys want to try hitting another conversation any time soon? I'm on vacation next week—I might be able to find some time.

**Comment by thepian** [comment]
I'm away Wednesday until Monday, but this time I'm in Europe, so hopefully I will have reliable WiFi whenever it takes place.
