### ISSUE TITLE
TypeError: Illegal access to a strict mode caller function.

### ISSUE THREAD

**Issue by greenpdx** [socketstream/socketstream#474]
I enabled the exports.authenticated in example.js.  When I run it I get "TypeError: Illegal access to a strict mode caller function."  I have read that the caller property is non standard.  I have not found any information on this.

I am using Chrome 39 on linux.

when I look at the vars is see that caller in _proto_ is null.

I am not sure on what is going on or how to fix it.

shaun

This is a copy of the scope vars, for local.

this: function()
arguments: Object
caller: TypeError: Illegal access to a strict mode caller function.
arguments: Array[0]
message: undefined
stack: undefined
type: "strict_caller"
__proto__: TypeError
length: 0
name: ""
prototype: Object
__proto__: function Empty() {}
apply: function apply() { [native code] }
arguments: null
bind: function bind() { [native code] }
call: function call() { [native code] }
caller: null
constructor: function Function() { [native code] }
length: 0
name: "Empty"
toString: function toString() { [native code] }
__proto__: Object
<function scope>
<function scope>

**Comment by paulbjensen** [comment]
Hi, Thanks for filing the issue. I'll take a look into it.

**Comment by greenpdx** [comment]
If there is anything I can do to help, please let me know.

**Comment by paulbjensen** [comment]
Hi @greenpdx,

I had a look at the issue that you mentioned. I haven't been able to replicate the error that you encountered.

Can I check the following? 

- That you generated a new SocketStream app with default settings
- What version of Node.js you are using (I am using 0.10.35)
- That the server/middleware/example.js file exists, and returns a function.
- That you uncommented line 10 in server/rpc/demo.js

Regards,

Paul Jensen

**Comment by greenpdx** [comment]
my nodejs is 10.25,  I will try to upgrade it.

shaun

**Comment by greenpdx** [comment]
I upgraded to 10.33.  the problem is node-debug.

When I run nodejs app.js  it works

If I run node-debug I get the error.
Now how to debug nodejs on the server without using node-debug?

**Comment by greenpdx** [comment]
Got the fixed.

thanks

**Comment by paulbjensen** [comment]
Hi, thanks for identifying more info about why it occurred. Does the issue still happen when running node-debug?

**Comment by paulbjensen** [comment]
I checked it with node debug app.js, it's working. Marking as closed.
