### ISSUE TITLE
issue with new static strategy

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#475]
I'm using this [laTrappe](https://github.com/kulicuu/laTrappe) for testing.

I've been drawing dependency off on a fork for some time, but now getting back into the master branch, (via another fork!), and noticing that all the commits after 

c0b41fea325b2cbda20e9d187bff864224894f50

are non-performing in one way or another.  

This is the app I'm using for test:

https://github.com/kulicuu/laTrappe

The latest commits seem to run fine but notice the `entry.coffee` file doesn't load-- basically the client doesn't load successfully.  

When I `git checkout` some commits like d2037735dbfc6b500af642993d5629e79fbd358c we actually get errors in the server console:

```
TypeError: Cannot call method 'use' of undefined
  at Object.load (/home/wylie/southernOcean/kulicuu/socketstreamDevs/laTrappe/node_modules/socketstream/lib/http/index.js:155:11)
  at start (/home/wylie/southernOcean/kulicuu/socketstreamDevs/laTrappe/node_modules/socketstream/lib/socketstream.js:102:10)
  at Object.exports.start (/home/wylie/southernOcean/kulicuu/socketstreamDevs/laTrappe/node_modules/socketstream/lib/socketstream.js:138:46)
  at Object.<anonymous> (/home/wylie/southernOcean/kulicuu/socketstreamDevs/laTrappe/laTrappe_local.coffee:35:35)
  at Object.<anonymous> (/home/wylie/southernOcean/kulicuu/socketstreamDevs/laTrappe/laTrappe_local.coffee:2:1)
  at Module._compile (module.js:456:26)

```

The later and latest commits seem to run well on the server side but the client doesn't load the entry file.

This commit f93652e4b16515d973a95ef59ab68ca6a4aef64c runs good.

**Comment by thepian** [comment]
Hmm, looks like I broke something with the static strategy.

**Comment by kulicuu** [comment]
Ah you got it cool !  I've been meaning to get to this, but also wondering  if anyone else could reproduce the error.  cool !

**Comment by thepian** [comment]
Sorry, didn't test it yet, was just apologizing as it seems to be my commits.

**Comment by kulicuu** [comment]
No problem and no rush at all ;}

**Comment by thepian** [comment]
I'd like to fix it. I'm not sure how to run your project though. tried calling

'coffee laTrappe_local' it cannot locate socket stream

Also you have a trailing comma in the package.son

**Comment by thepian** [comment]
I'm not sure what to expect with La Trappe. I see issues with Angular template script tags having IDs with the file path, which surely they shouldn't have.

**Comment by thepian** [comment]
Could I ask you to make a detailed bug report. Ideally a test setup that fails. We really want to move towards TDD.

**Comment by kulicuu** [comment]
Cool cool I'll do that tomorrow.

**Comment by kulicuu** [comment]
Right so here it is tomorrow.
I've fixed laTrappe and so you should be able to run it locally. 
I've created a new clone of it and added the line `"socketstream": "git://github.com/socketstream/socketstream.git#master",` to the _package.json_ flie.
The detailed bug report without inserting logging debris is _Nothing_.  There is no error output in the server console, and there is no error output in the browser console.  
Looking at the differences between the html page source as delivered we have:

###### Bad
```
<!DOCTYPE html><html lang="en" ng-app="laTrappe"><head><script src="/_serveDev/system?ts=1422794514966" type="text/javascript"></script><link href="/_serveDev/css/laTrappe_local_alpha/main.styl?ts=1422794514966" media="screen" rel="stylesheet" type="text/css"><script src="/_serveDev/code/laTrappe_local_alpha/entry.coffee?ts=1422794514966&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/laTrappe.coffee?ts=1422794514966&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/angular-animate.js?ts=1422794514966&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/angular.js?ts=1422794514966&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/lodash.min.js?ts=1422794514966&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/start?ts=1422794514966" type="text/javascript"></script><script type="text/ng-template" id="panel.html"><button ng-click="authMe()">authMe</button><button ng-click="deAuthMe()">deAuthMe</button><button ng-click="pingProtected()">pingProtected</button></script><script type="text/ng-template" id="placeholder.html"></script><title>laTrappe</title><meta charset="utf-8"></head><body ng-controller="laTrappe"><panel></panel></body></html>

```

###### Good

```

<!DOCTYPE html><html lang="en" ng-app="laTrappe"><head><script src="/_serveDev/system?ts=1422794740752" type="text/javascript"></script><link href="/_serveDev/css/laTrappe_local_alpha/main.styl?ts=1422794740752" media="screen" rel="stylesheet" type="text/css"><script src="/_serveDev/code/laTrappe_local_alpha/entry.coffee?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/laTrappe.coffee?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/angular-animate.js?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/angular.js?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/lodash.js?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/code/laTrappe_local_alpha/lib/smoothie.js?ts=1422794740752&pathPrefix=laTrappe_local_alpha" type="text/javascript"></script><script src="/_serveDev/start?ts=1422794740752" type="text/javascript"></script><script type="text/ng-template" id="panel.html"><button ng-click="authMe()">authMe</button><button ng-click="deAuthMe()">deAuthMe</button><button ng-click="pingProtected()">pingProtected</button></script><script type="text/ng-template" id="placeholder.html"></script><title>laTrappe</title><meta charset="utf-8"></head><body ng-controller="laTrappe"><panel></panel></body></html>

```

**Comment by kulicuu** [comment]
Okay,

here is the good delivery of the code module: (accessed by ctrl-u for the source in Firefox and then clicking the link on first script.

https://gist.github.com/kulicuu/27206afb11851733d4e8

The bad one just gives the error CANNOT GET.  

So that's basically the bug report as far as that goes.  

For something more substantial, I could hunt around with my console logging gear on the server side.  Will get back to you.

**Comment by kulicuu** [comment]
###### Update 
I've made another clone to analyze the new static work, not only to debug regarding this issue but also to see your development line here and to think about how to integrate with new work I'm doing with respect to the React integrations.

**Comment by kulicuu** [comment]
Hey, I want to find the discussion leading up to the development of the new static strategy; where would that be ?  
Or /and, could you describe -- briefly or at length -- what you had in mind to accomplish with the new static strategy ?

**Comment by kulicuu** [comment]
Wow, cool code.  Lots of work here, not too sure raison d'etre yet, but lots here and it's very interesting.  Noticed will require some modifications (not too difficult) to bring it merge-able with the new Connect v3.3.4, and some of the files modded are the same.  
Have you been able to reproduce the error I'm encountering ?  Again, it's serving the view but not the Javascript, so the entry file is never initialised.
laTrappe should be working now let me know if still any issues there.

**Comment by kulicuu** [comment]
Okay the problem was with the way I was integrating the Express and SocketStream stacks, as seen [here](https://github.com/kulicuu/laTrappe/blob/454693673aabf6392d04dfeb49bee11afe174741/laTrappe_local.coffee#L24).  
I'm okay with dropping this usage and finding a better way.... at any rate it's on my thingstodo list to implement an upgrade to Express v4 and that will require some reworking anyway.  So I'm going to close this.
Thanks!
