### ISSUE TITLE
socketstream new with coffee option should provide app.coffee instead of app.js

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#479]
I noticed that when trying to build a new SocketStream application with CoffeeScript, the root directory app file is returned as a Javascript file, rather than a CoffeeScript file.

It feels like it should be a CoffeeScript file.

**Comment by kulicuu** [comment]
It's been like that since forever I think.  I haven't used the Commander/terminal interface for some time now, so it doesn't really affect me at present, but it's on my list of things to get to.  After the engine;io and connect.

**Comment by paulbjensen** [comment]
I think this would be worth separating out for 0.4, so that SocketStream's codebase becomes a bit more manageable.

**Comment by thepian** [comment]
Won't fix as ES6 is the future. Pull requests welcome though
