### ISSUE TITLE
ss.client.set({liveReload: ['views', 'css']}); does not affect monitoring of directories.

### ISSUE THREAD

**Issue by lafras-h** [socketstream/socketstream#480]
Tried with version 0.3.11

ss.client.set({liveReload: ['views', 'css']});//DOES NOT WORK TO IGNORE STATIC FILE CHANGES
//debugging in live_reload.js
//    _ref = options.liveReload; 
//    console.trace("Stack!",_ref); //debug
//shows ss.client.set did not affect the array

//ss.client.set({liveReload: false}) //WORKS FOR PRODUCTION

I would ideally like to ignore changes in a sub directory of static

**Comment by paulbjensen** [comment]
Thanks, I'll look into it.

**Comment by thepian** [comment]
Perhaps this could be the task to add a couple of tests for live_reload

**Comment by paulbjensen** [comment]
Agreed.

**Comment by thepian** [comment]
Btw, I just saw live_reload kicking in while running tests. We should also find a way to make it inert while running the tests that do not depend on it being active

**Comment by lafras-h** [comment]
The default parameters are almost identical to the original live reload, so the tests should be affected the same, alternatively set the delay very long, or disable altogether.

**Comment by thepian** [comment]
I'm sure it's trivial, just a reminder to do it :)
