### ISSUE TITLE
interesting line in 

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#481]
Realising the _engine.io_ upgrade situation can't be isolated from the upgrade situation with the whole of SocketStream, today I've been reading through the entire framework-- focusing especially on modules _request_, _session_, _websocket_, and _client_.

Came across something funny... 

From _/request/middleware/index.js_:

`existslib = process.version.split('.')[1] === '6' && require('path') || require('fs');`

0:  Exactly what is being done here and why ?  I understand testing for the version, (but why going for different library based on that ... ah nevermind ;) )

1:  Do we still need this (line) ?

**Comment by paulbjensen** [comment]
That looks like a line that is inspecting the version of Node.js to see if it is version 0.6.

The line can be simplified to require('fs'), and rename the variable to 'fs'.

**Comment by kulicuu** [comment]
Pretty much so yes. ;]

**Comment by thepian** [comment]
Is there any reason to support node 0.6 ?

**Comment by kulicuu** [comment]
In my opinion no.  Paul's response implies concur.  
It's not a big issue at all -- but it is a small issue, and I'm going through the whole framework now, so thought it would be fun and productive to relate findings.  This was one of them.

**Comment by kulicuu** [comment]
I've changed the line in pr #478

**Comment by paulbjensen** [comment]
Cool, will close this, and wait to get it in when the PR is merged.

**Comment by thepian** [comment]
I fixed it in master as well while fixing up some require vars
