### ISSUE TITLE
Change var declaration convention in code

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#482]
I think there should be a change in the style of variable declarations. I assume they are a product of the move from CoffeeScript to JS, and not an intentional decision. My main motivation is that it goes against common ways of writing JS, and prevents the use of function hoisting which allows you to place internal functions after the place that they are used.

1) Wherever possible functions should be declared in the classic way and not as variables.
2) Variables should be declared where they are used and not at the top of the module except for module wide variables and imports.

These guidelines should not be seen as religion, but rather as a default, and should in effect be seen in 90+% of the codebase. If you are finding yourself sticking to them only occasionally, you are doing something wrong.

**Comment by paulbjensen** [comment]
Hi Henrik,

Yep, it was a result of converting the code over from CoffeeScript, hence there is room to optimise the codebase.

**Comment by thepian** [comment]
Made some improvements
