### ISSUE TITLE
New branch for 0.4

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#483]
We should have a new branch for the next major release. It could be named future, beta, next or major.That way completed features can be merge in, and master can be kept for minor fixes and tweaks meant for the next minor release.

There should also be milestones for 0.3.12 and 0.4

**Comment by thepian** [comment]
As it seems 0.3.12 is the new next release, I would suggest also making a 0.3.13 milestone. Some improvements might be pushed in the future while we are preparing 0.3.12

**Comment by paulbjensen** [comment]
Done, created.

**Comment by paulbjensen** [comment]
I'd suggest "next" in honour of Steve Jobs.

On 3 February 2015 at 16:59, Henrik Vendelbo <notifications@github.com>
wrote:

> Thanks. How about the idea of having a separate branch used for the next
> major release? I'm not sure what name to suggest
>
>    - future
>    - major
>    - next
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketstream/socketstream/issues/483#issuecomment-72688723>
> .
>



-- 
Paul Jensen
07914 171 345

**Comment by thepian** [comment]
of course!
