### ISSUE TITLE
question on line 105 in socketstream.js

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#484]
`client.load(api);`

However, (and please correct me if wrong) the function definition as I see it in [client/index.js](https://github.com/socketstream/socketstream/blob/master/lib/client/index.js) on line 181 takes no arguments.

One sort of almost esthetic point:  I disfavor the idea of sending to any client related modules the systems' entire api object on the principle that it's _a bad idea_.  Interested in other views.

**Comment by kulicuu** [comment]
Cool response.  I'll have to come back to this fresh later for further discussion and exploration.

For now I can say more good news: I got the new _connect_ working.

**Comment by thepian** [comment]
Excellent. I seem to have Express 4 working, but haven't really gotten to a well rounded setup. Sounds great if we can base things on the latest connect.

Does this mean that we should make a connect based Router rather than our own Router implementation ?

**Comment by kulicuu** [comment]
I'm listening I think you have the parts I'm missing.  I mean your ideas indicate auspicious devv strategies, seems likely to me.    As for certainties, it's all very preliminary.  Connect 3 is working.  I haven't been able to get my app working on Express  4 yet, would like to see the Gisttt of this.

**Comment by kulicuu** [comment]
I'm thinking of leaving Express out of my apps in the future.  Wasn't really sure what I thought I needed it for-- just wanted to explore its API I think.  Still I mighth like to get 4 working, to create a how-to doc for it.

**Comment by arxpoetica** [comment]
This is going off topic, but since you all have already, I think we need to build in something to SocketStream that allows for Express-like pages—maybe this should be a feature request. But I've been thinking more and more that *many* applications that are single page end up needing routing that doesn't end up utilizing the web socket. Again, conversation for another thread. I'll open up a ticket and we can brain dump there.

**Comment by kulicuu** [comment]
@arxpoetica  I have this already in the sense that I have the unified Express/SocketStream in all my apps for at least year.  (See _britvic_)  
You are right in that many aspects of a system don't need to utilise the websocket.  I was using it (the Express component) first of all the serve single page Angular  apps for gate and authorisation pages-- e.g. why load the entire single page app  to unauthorised users ?  
Now I think I could probably figure out how to meet my needs with just Connect, but people building out large HTTP APIs alongside their WebSocket thing might want Express.  So yeah.

**Comment by thepian** [comment]
This is a good discussion, but can we change the title to something actionable. Having tons of unresolved issues detracts from the project

**Comment by kulicuu** [comment]
I was hoping to close it as it's fixed in PR #486
