### ISSUE TITLE
Drop JSON shim

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#485]
1) It's redundant in 99.5% of all browsers out there.
2) Your app isn't going to work anyway on IE6/7
3) It's annoying to have multiple JSON shims slow down a page
4) It shouldn't be duplicated in page specific JS, but be served in a site-wide shim

**Comment by paulbjensen** [comment]
yep, let's do this.

**Comment by kulicuu** [comment]
Cool..

**Comment by arxpoetica** [comment]
:+1:

**Comment by thepian** [comment]
Will go in with the bundler
