### ISSUE TITLE
live_reload.js ignores multiple changes

### ISSUE THREAD

**Issue by lafras-h** [socketstream/socketstream#487]
The onChange  event in live_reload.js ignores  multiple changes very simplistically causing it to ignore the last change if it happens between checks, this should rather start a timer of 1 second and keep resetting it  as it finds changes, then when it expires send the publish.all.

I noticed this when I was looking for a way to temporary disable live reload, to prevent multiple
"Client files changed. Reloading browser..."   while my SQL-MVC compiler generates files.

There is none .. it would be nice to have..maybe allow the user to insert callback  before the  ss.publish.all('__ss:' + action); is sent, and only publish.all if it returns false (un-handled),

I hope to later be able to publish changes only to users that are currently on the files that are being updated, so if I could intercept the publish it would be great..

**Comment by thepian** [comment]
Would you be able to
1) Clone the repo
2) Make proposed changes / fix
3) Make a pull request for your repo

Even if we tweak your solution, it sounds like a completely reasonable feature request.

**Comment by thepian** [comment]
@paulbjensen Is this now fixed ?

**Comment by paulbjensen** [comment]
I merged a PR from @lafras-h about 1-2 weeks ago, which I tested manually and it works but I don't think it added any automated tests.

This can be marked as closed, and as for automated tests, I can take a look into it.
