### ISSUE TITLE
Routing for non-web-socket pages.

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#488]
SocketStream has until now had an event based Router. In 0.5 this is being replaced. Routing will come back in some other form in 1.0
If you want classic routing let the ExpressJS example be your guide. If you just need to chain middlewares consider using connect. The `ss.http.middleware` is still returning a connect instance, but to use it you must add connect as an app dependency.

@arxpoetica please comment

Current plan:

- [x] New caching middleware for client assets & static resources
- [x] Support on demand and workers
- [x] Reloader updates cache when source files change
- [x] Example routing with Connect and Express
- [x] Set a direction for subscribing and managing permissions for URLs
- [ ] Tweak dev-time paths to expose source-filename in browser
- [x] If tasks fail log it by default (or let Gulp handle it)

### Original Text

The current thinking/strategy for building out static assets and/or public-facing pages that don't involve web sockets is to couple SocketStream with Express (or an equivalent).

This may continue to be the right solution (though if we continue that path, I'm in favor of exploring other possibilities like Koa, etc.).

Express is a time worn solution, but it also feels a little kludgy in that there are conflicts or routing concerns that easily crop up when bootstrapping SS with Express. 

It would be good to consider building something into SocketStream that allows for more routing possibilities. The Sails framework, for example, gets something right in this regard where routing is an implicit concern, and web sockets are made available—on any page. SocketStream *is* concerned with single page applications first and foremost, but in the real world of development, most websites need something more static. I think it's right to continue to approach SocketStream as "the" (or "a") solution for realtime apps—but SS probably doesn't give enough consideration to routing, as a framework.

See https://github.com/socketstream/socketstream/issues/484#issuecomment-73048430

**Comment by kulicuu** [comment]
I was thinking of something similar yesterday.  Will be thinking about it this next week as going through the whole system.

**Comment by thepian** [comment]
I think single page applications are just the latest fad. They've been my bread and butter for most of 7 years, but they are a vertical solution hosted within a multi-page reality.

I think the two will merge as streaming becomes more widely adopted. 

I personally want Socketstream to fit well in a multi page app world.

**Comment by kulicuu** [comment]
One approach I'd been considering but never got around to implementing on the system for which I'd had it in mind was to issue single page apps the way the olde http systems served single views in a system, in the sense that sessions would be shared and redundant resources would get traded off on client-side cache.  The immediate application for this is to have a major distinction between landing page app / 'gate' app, and the main app interface as for authorised 'normal' users.

**Comment by kulicuu** [comment]
I like the fads, provided they are driven by sound engineering intuition.  I think it's a good sign that we have so much ecological richness in the whatever.  Those that persist -- like Express -- are well honed.

**Comment by thepian** [comment]
I don't mind the fads. However I am wary of spending energy on them before they hit critical mass

**Comment by kulicuu** [comment]
good point.

**Comment by thepian** [comment]
After getting stuck with a refactoring blunder, I'm really curious about routing alternatives for the dev-time middleware. Is Koa or Sails and easy option? or does it require a lot of thought/discussion. I'd prefer to keep all principal / fundamental changes optional to have good continuity.

**Comment by kulicuu** [comment]
I don't understand your term dev-time middleware .

**Comment by thepian** [comment]
_serveDev is partially for dev-time only. My thinking is that it should be a specific middleware only loaded in dev. It is at least conceptually.

**Comment by paulbjensen** [comment]
If you want routing, it's possible to deliver it as connect middleware, and not require express at all. Originally it was in connect's core, but then pulled out, and then someone turned it into a middleware you loads via npm. That's how I got Dashku to work alongside loading a REST API as well.

I think maybe some documentation around how to do this would be useful.

Should we look to support other options? Perhaps. In my experimentation with the core http server about a year ago, I stumbled across a more efficient level of support for routing than using connect. It was a project named 'vorka', I'd be happy to pull it up and have a look at it.

**Comment by kulicuu** [comment]
I'm not sure why I failed to mention this before, but this routing for non-Socket pages is precisely why I went initially to integrate Express with SocketStream, which yields the effect.

@paulbjensen approach even better in the sense of lighter weight, although I suppose some people really want a full Express app alongside the SocketStream stuff.  Documenting the practice would be great.

Anyways, I'll be working on the Express4 demo-app and/or docs as I just got that working.

**Comment by arxpoetica** [comment]
Sorry, @thepian somehow I missed this. Koa is probably *not* the right solution—*yet*—it uses generators which solves a whole host of middleware/connect issues. The problem is that `Koa currently requires node 0.11.x for the --harmony flag which exposes generators to your script.` And only in 0.11.x and up. So it's *iffy* in the present—but maybe still something to look at.

Sails is a full on framework, so not applicable here. I was only referencing it as they have a very well-thought-out routing system (fully REST-ful, MVC, fleshed out routing policies, etc.) which borrows heavily from Rails. I've been tinkering with it the last few days, quite impressed with the way it handles routes *and* exposes sockets, which was what set off this thread in the first place.

@paulbjensen url for `vorka`?

**Comment by paulbjensen** [comment]
I didn't put it on Github, I'll dig it out from my disk backup and post it.

**Comment by arxpoetica** [comment]
gotcha.

**Comment by arxpoetica** [comment]
FYI, I'm currently digging into Koa over here: https://github.com/socketstream/ss-examples/tree/master/ractive-jade-koa. I haven't pushed anything up yet, but I will soon. I may ask for a hand and opinions soon.

**Comment by thepian** [comment]
Should we replace our Router impl with some existing npm module like 'routes-router' ?

**Comment by arxpoetica** [comment]
I think that's a good idea—granted that we still allow for defining clients.

**Comment by afrozl** [comment]
@kulicuu - does anything special have to be done to integrate socketstream with Express4?

I am attempting to integrate socketstream (Dashku) with Express (keystonejs) and running into issues 

https://github.com/dashku/dashku/issues/64

**Comment by thepian** [comment]
@afrozl ss-examples has one for Express4, it is aimed at SocketStream 0.5 which is not stable yet.

**Comment by thepian** [comment]
@arxpoetica Have you looked at some of the changes? Any thoughts?

**Comment by arxpoetica** [comment]
Point me to the changes and I'll give you some opinions. :)
