### ISSUE TITLE
automated acceptance (&e2e) testing system for development

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#489]
I suppose using some sample app built as test-app into the development repository, and would be engaged with headless browser to run some routine covering the whole range of use cases and feature implementation types.

**Comment by thepian** [comment]
I agree. It is next to impossible to keep a robust implementation without that.

Ideally it would be twinned with default project generation, the default project skeletons are used to test the framework, and they are tested at the same time.

**Comment by kulicuu** [comment]
I've had good luck with this http://angular.github.io/protractor/#/, and I think it should work for non-Angular apps as well.  Anyways I'm starting a branch to work on this.

**Comment by kulicuu** [comment]
will use this thread for todo list on features -- i.e. defining the acceptance criteria for SocketStream functionality.

##### list of constraints (prelim draft)

- should serve the app
- sessions should persist over browser reloads 
- sessions should persist over server restarts (assuming redis sessions)
- websockets should work if availablbe (tests should query engineIo on low level api or something custom to effectively guage)

**Comment by kulicuu** [comment]
I guess to make a protocol where pretty much anyone can register an app within the e2e folder under like `/some_apps/someones_test-app_1/`.  

Objections ? (for prototyping anyways)

Will be interesting because of implications for development environment.  Now my test app will embedded in the repository itself, and local file relations will reflect that; currently my test app (laTrappe) is the parent by way of node_module the socketstream development folder.  So that would be different.

**Comment by kulicuu** [comment]
Starting to wonder if better to bring them in as node modules via devDependencies.

**Comment by thepian** [comment]
I think you should have an examples directory with a separate package.son, otherwise I would suggest a separate repo called "socketstream-demo".

**Comment by kulicuu** [comment]
There's a PR with the solution in [submodules](http://git-scm.com/book/en/v2/Git-Tools-Submodules).

I think it will be best.

**Comment by thepian** [comment]
When do you see us have the first version of this ready, for 0.3.12 or 0.4 ?

**Comment by kulicuu** [comment]
I think it's kind of there already, in the sense that the minimally viably productive manifestation of the feature structure on the app structure is just to be able to manually do acceptance testing over a range of developers' apps, initially your own.

**Comment by kulicuu** [comment]
Then you can add automated acceptance testing as you see fit, in a way that's specific to this SocketStream dev environment and your app's structure.  I'll be using Protractor for this particular (angular) client of laTrappe's.  I'll probably keep adding clients to lT in other frameworks-- fashionable experiments.

**Comment by kulicuu** [comment]
Good to remember in this situation the feature isn't for the notional primary consumer of Ss, but for the developer of Ss.
