### ISSUE TITLE
/assets vs _serveDev

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#491]
After looking at #438 I've been thinking that the _serveDev scheme should be revised. However I'd like some consensus on this to avoid anyone feeling that we are changing everything without good reason.

I started an ngdoc to outline the logic of a revised scheme.

https://github.com/socketstream/socketstream/blob/feature/465-bundler/src/docs/tutorials/en/url_scheme.ngdoc

IMO the serving at dev time should,

1) Contain a cache busting query
2) Flatten individual CSS files to be at the same level
3) Allow relative paths to files in static assets
4) Be in a similar location in production and development

Having sane relative paths to images and fonts is a common problem, so I think we should try to support that.

When you look at the URL for HTML/CSS/JS files output vs served in development, they are very different. I think that is undesirable.

**Comment by kulicuu** [comment]
I really don't know enough about this yet to make an informed comment.  Sounds good.

**Comment by thepian** [comment]
Paul, are you Ok with this ?

**Comment by paulbjensen** [comment]
@thepian hi Henrik, yes, it makes things simpler.

**Comment by thepian** [comment]
The pull request is basically done. Just need to add tests to make sure I haven't broken too much. Feel free to check it out.

**Comment by thepian** [comment]
I've merged with latest master and I have a lot of tests blowing up. If @kulicuu, @lafras-h or @paulbjensen could lend a hand tracking down the issues that would be great. If not I will figure it out.

**Comment by thepian** [comment]
sorted
