### ISSUE TITLE
Add notes for contribution on feature branches

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#493]
When / how should I be doing this ?  Wondering about convention or protocol.

I've been creating PR to master branch and would like them maybe to go into feature branches for awhile until really tested well.

**Comment by thepian** [comment]
I try to follow "git flow" convention and make a feature branch matching an issue. Not sure what else to do.

I see no problem with having many branches. They should be kept alive though, or they might end up diverging too much. However even then they can be used for reference or revived.

**Comment by kulicuu** [comment]
Ah cool yeah I should study that _git flow_ thing more.  
And I'll start making feature branches then.  (wait though, are you saying branches can't be terminated when their feature is merged to master branch ?)

**Comment by thepian** [comment]
By alive I meant: up-to-date with the latest master or next branch (depending on whether they are for the upcoming minor or major release)

**Comment by kulicuu** [comment]
cool understood.

**Comment by thepian** [comment]
We clarify this in docs
