### ISSUE TITLE
What is wrong with branch: features/465

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#494]
Can anyone spot what I messed up on the feature branch for #465 ?

Once checked out you can run it with a project (easy way to do that is to use 'npm link' in the checked out socketstream and 'npm link socketstream' in a project of yours).

If you load a view you should get 404 for all the assets in development. Somehow it's not serving correctly. I can't spot what I broke. It's in checkin 9b7cb47e somewhere.

**Comment by paulbjensen** [comment]
I'll have a look tonight.

**Comment by kulicuu** [comment]
I've fetched this branch, npm-installed, and running laTrappee under it serves fine.

**Comment by thepian** [comment]
hmm, interesting

**Comment by thepian** [comment]
Fixed a typo

**Comment by kulicuu** [comment]
I just realised my test was no good, because of the way my new development environment is set up.  I need to adjust it somewhat.
