### ISSUE TITLE
Internal ss.log interface for plugins, formatters and other extensions

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#497]
The information passed when packing and serving should be logged with this interface. Warnings should be logged through this.

There should be specific functions for each use case of logging in Socketstream.

Formatters should adopt a streaming interface that allows for error feedback to Socketstream. 
As discussed in #469 

- [x] test coverage formatters
- [x] test coverage template_engine
- [x] Logging errors + stack traces and showing issue number logged in the asset result
- [x] For debugging mode show error in browser

**Comment by paulbjensen** [comment]
Agreed. I think the challenge here is to get the ss variable to be passed and loaded into the various other places where console.log is being called. It will require some internal rewiring in order to achieve that.

**Comment by thepian** [comment]
Can you elaborate. As I understand the `ss` variable, it is a simple object with a very limited API to be used by the Socketstream internals, plugins, formatters etc.

Are you concerned that dev-time reload will be problematic? 

To me ss seems like a good idea as it can be cleared and reinitialised if needed. And it allows making new functionality available without adding parameters to a lot of source files.

It seems the alternative is a complete move away from the current style for implementation of the internals following

     module.exports = function(ss,options) {
     }

**Comment by thepian** [comment]
My solution is to offer a new API where formatters and template_engines are functions that return an instance. They could actually be called with new. That way you can supply a factory function or a constructor, and either will work.

The old API with init call will work unchanged for 0.3

I will try to use a streaming approach like in Gulp so they can be used as part of a build chain as well.

**Comment by thepian** [comment]
@RomanMinkin Didn't you make an Angular template engine? Are you using suffix and prefix?

**Comment by RomanMinkin** [comment]
@thepian , no i made this one https://github.com/RomanMinkin/ss-angular-templates it uses custom formatter function.

I like streaming idea API idea. What do you think about https://github.com/isaacs/node-glob or https://github.com/wearefractal/vinyl-fs?
`gulp` uses the second one.

**Comment by thepian** [comment]
I tried vinyl-fs long time ago. I find streams a bit difficult to Grok, so perhaps it is something to have under the hood and not in the default interface. What I really like is the notion that one file might result in multiple files as output.

My current approach is to stick with the current callback api and support returning an Error instead of throwing it, as the throwing is incompatible with async.

I thought of a promise like (resolve,reject) semantic, but I don't think it adds any power. I think the streaming could be introduced as an internal principle allowing easy extension/integration with gulp tasks. The templateEngine and formatters would run unmodified, but support an alternate API for direct stream implementations.

@RomanMinkin So only selectFormatter but no suffix or prefix?

**Comment by RomanMinkin** [comment]
@thepian i did not use them, i found custom template function more powerful.
