### ISSUE TITLE
Unique client ID at each run

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#498]
The current Client View ID is a simple timestamp, and is therefore only sure to be unique per run across clients, but not between them.

I changed it to be generated as a string using the npm `shortid`. I use it to identify the client bundler during development without adding the client name to the URL.

Any thoughts, objections, jubilations to this ?

**Comment by kulicuu** [comment]
Jubilations.

**Comment by paulbjensen** [comment]
This sounds like a good change. Please proceed.

**Comment by thepian** [comment]
will be merged as part of #465
