### ISSUE TITLE
React & Flux app integration capabilities, + demo app

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#500]
I'm working on integrating a React app, which is an interesting technical exercise.  React has no templates, and uses a unique language hybridising JS and HTML.  
Initially I'm going with the CoffeeScript integrations: e.g. [coffee-react](https://github.com/jsdf/coffee-react),[coffee-reactify](https://github.com/jsdf/coffee-reactify), but also planning to do the Vanilla/ES6 version.
Necessarily then, will require some work in the core client system.  
If possible I'll decouple this and it would be an optional addon module. It may only require another client formatter e.g. [jokagent/ss-react](https://github.com/jokagent/ss-react), and [DeLaGuardo/ss-jsx](https://github.com/DeLaGuardo/ss-jsx)

some more google-located resources:
https://github.com/stratospark/react-ss

**Comment by arxpoetica** [comment]
LIKE.

**Comment by kulicuu** [comment]
Both @jokagent 's and @DeLaGuardo 's libs work fine as far as I can tell; the latter even allows to pass coffee-script files into the mix.  

I'm tempted to close this issue now, but going to research+develop a bit more to see what is possible -- e.g. my next step is to verify that I can pass .csx files through @DeLaGuardo 's system and have them work.  Also to see how the other libraries linked above are relevant to Ss.

Really should do a small demo as well-- could pass for it to be documented.  Do we have some kind of library for canonical demos ?

**Comment by thepian** [comment]
Sounds nice. I would love to see an example of that.

@paulbjensen I'd like to reiterate a request for a second GitHub repo 'socketstream/examples' for this sort of stuff, we could put it on npm as `ss-examples`.

**Comment by kulicuu** [comment]
thanks & Yes, cool idea.

**Comment by paulbjensen** [comment]
@thepian that's fine, please go ahead.

**Comment by kulicuu** [comment]
Somewhat off-topic --except for the demo-app discussion-- > 

Good news: I now have Express4 working with the newest SocketStream.

Haven't cleaned the file yet: https://github.com/kulicuu/laTrappe/blob/sIGG/lT_reactVanilla_local.coffee

It was a strange hack as it required starting a dummy server (not the one that will be listened on) just in order to get the `ss.http.middleware.stack` object.  If that's bad hard on resources maybe could put another function into the http module just to get that object without starting a server.

**Comment by arxpoetica** [comment]
Dude. You are rocking it. :dragon:

**Comment by thepian** [comment]
I've made the repo to put this in,

https://github.com/socketstream/ss-examples

**Comment by arxpoetica** [comment]
Awesome. I'm going to do a Ractive.js example at some point.

**Comment by kulicuu** [comment]
@arxpoetica ha thanks!  Actually my Express4 implementation needs work, but hopefully by early next week a demo will be up. 
@thepian ditto(Awesome).
