### ISSUE TITLE
Make 0.4.x ready for release

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#507]
This is a place to collect things TODO to get the `0.4` completely done. Will take a couple of minor releases

* [x] Merge fixes for live reload
* [x] Merge connect/express improvements
* [x] Default bundler can load code module as name, name/entry.* or name/index.*
* [x] Start will kick off the correct module
* [x] Default entry init added to start automatically not using system assets
* [x] Dev time loading of system modules
* [x] Packing logic: options.packedAssets vs options.packAssets vs client.packAssets(opts)
* [x] browserify.js is added by default bundler
* [x] Ensure no regression for ondemand support
* [x] Ensure no regression on web worker support
* [x] Unit tests for web worker support
* [x] Unit tests for template engine running of a directory
* [x] Full unit tests for constants and locals
* [x] Test non-standard extensions for formatters (I.E. jade)
* [x] Full unit tests for packing
* [x] Tests and Docs for on demand serving
* [x] Docs for writing formatters with support for constants and locals
* [x] color support
* [x] Document upgrading formatters to use logging and returning errors
* [ ] Contact plugin writers about updating to v 0.4
* [ ] Document installing and using npm modules in client dir #287
* [ ] Document reloading the app configuration with nodemon #466 

Advise 3rd party of upgrade

- [ ] less formatter
- [ ] jade formatter
- [ ] coffee formatter
- [ ] coffeekup formatter
- [ ] stylus formatter
- [ ] ss-hogan formatter & engine
- [ ] ss-coffeekup
- [ ] ss-ractive
- [ ] ss-handlebars-formatter
- [ ] ss-toffee

# Changes in the Release

The way views are served has been updated. The *default bundling of assets* is largely as before, but some details have changed. The major change is that the bundler of a client definition can be changed. You can configure this on a per definition basis. For more information look in the tutorial section.

Please note that due to the changes, however carefully they have been done, you should not deploy this release in production. We expect to find issues and fix those in a maintenance release 0.4.1, which can hopefully be considered fit for production. However, if you are developing and your next deployment is a couple of months off, it is a great time to upgrade to version 0.4.

If you are used to web app development you will know *Bower*. In this version we have made improvements to work better with Bower. The most obvious one is you can now define your client assets using relative paths within the client. So if you put `bower_components` in the client directory you can refer to them in the definition by `"./bower_components/<module>/<file>.js"`.

Changes to consider.

* You can make your own custom bundler
* CSS files can reference images and other assets using relative paths in development and production
* You can refer to Bower components in your definition
* JSON shim dropped. To support IE6/7 you must manage it yourself.
* `client.id` is unique and not a plain timestamp
* Plugins should use the new log interface on `ss.log`.
* You can load npm modules in the client by maintaining node_modules in the client directory.
* You can configure global constants to be shared between the client definition and browser code.
* By default the initCode for a view is executed at the end of the body independent of the SocketStream tag.

**Comment by kulicuu** [comment]
:)  I will find time to contribute to this sometime this week.  May be small, but I will.

**Comment by thepian** [comment]
60% coverage btw. Yes I know even at 100% it won't be enough, but it's rising.

**Comment by thepian** [comment]
Only thing outstanding is nodemon. I don't have time to document, but anybody is welcome to do it.
