### ISSUE TITLE
writing from client to external db via RPC

### ISSUE THREAD

**Issue by auch188** [socketstream/socketstream#511]
Hi I'm new to socket stream and posted on the google groups site. I'm not sure if I should be posting an issue but I wasn't getting an answer in google groups.

I was trying out socketstream and wanted to write to an external db. I read the documentation and followed the instructions by writing code in the main app.js file as follows;

```javascript.
  var db = require('redis'), 
  client = db.createClient();
  ss.api.add(db, client);
```

I then tried to call the db api in the server/rpc/example.js file I had with

``` javascript
  ss.db.set("User", user)
```
where user is a variable used to capture username input from the client.

For some reason my program is not recognising the api and is spitting out an error of undefined.

What might I be doing wrong?

**Comment by kulicuu** [comment]
Try `ss.api.db.set("User", user)` and generally alias it .

**Comment by paulbjensen** [comment]
Try <code>ss.api.db</code> instead of <code>ss.db</code>

**Comment by thepian** [comment]
Where are you accessing this DB? The ss.api is passed to plugins as the variable ss.

From your application, I'd expect you to have a module that exports the database client so you can share it among app modules without involving socketstream.

**Comment by auch188** [comment]
Hi guys

Thanks for the replies. I figured it out. I needed to call my external Redis db instance directly from the server in my server/rpc/example.js file instead of using ss.api.db.

Please close
