### ISSUE TITLE
Let's break out the docs, yes?

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#513]
We started to do that at one point. Right now they all sit in this repo, which is fine, but it'd probably be best if they're separate from the main engine (IMO). That way we can structure the setup however we need to.

Let me know your thoughts. In the meantime, I've checked them out to start to make improvements to them.

Side note, I know @RomanMinkin did a lot of work on them at some point, which was great. Can somebody fill me in on how the process involved to get changes online, etc.?

**Comment by paulbjensen** [comment]
The docs are generated by a grunt task, and pushed up to the gh-pages branch on Github.

The reason that the docs were put with the code is because they generate documentation from the code comments. Here is an example: http://socketstream.github.io/socketstream/docs/#/api/http.index:index

**Comment by arxpoetica** [comment]
Ah, okay that's quite a trick. Makes sense to leave them as is then. I'll close.

**Comment by thepian** [comment]
Actually I think writing articles about how to use Socketstream on other destinations is much more important. We should actively try to extend the community. The docs are not great, but they mostly do the job. The ideal would be to recruit someone that has helped make stellar docs on another project.

**Comment by arxpoetica** [comment]
@thepian I have more to say. I'm going to open a new ticket w/ a more general "improve docs" question.
