### ISSUE TITLE
template engine use, how should it work?

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#514]
I'm writing tests and tweaking the functionality, and it seems I broke something, so I need clarification.

If I understand it correctly the use call sets the engine to use for all views. How is that set? It doesn't seem to change defaultEngine.

I'm contemplating creating the client object with a prototype of defaults. One of the defaults would be the templateEngine. That would allow bundlers to set their own default template engine by setting it on the client.

I think the ideal for a template engine to have a path matching variable or function that will determine if the engine supports that type of template. I suppose this way you could even support multiple template types in the same view.

@paulbjensen Please advise

**Comment by paulbjensen** [comment]
@thepian I'll take a look now

**Comment by thepian** [comment]
I didn't break it, just wrote a bad test, however the question remains; Fundamentally.

Are we happy with the current logic?

You can assign a template engine to a path. By default it is root. (is root the client dir?)

You can't assign it to an extension or a pattern. Perhaps it could be a combination of,

* The engine suggests a file name pattern or extension
* The app assigns it to a FS branch.

**Comment by thepian** [comment]
Pushed the tests to the logging branch. We still need tests for subpaths and for custom template engines.

**Comment by thepian** [comment]
Do we know of any engines that rely on prefix/suffix of template markup?

**Comment by thepian** [comment]
I think I understand it now
