### ISSUE TITLE
socketstream breaks apps when used with iojs 1.6.x

### ISSUE THREAD

**Issue by luksch** [socketstream/socketstream#515]
it seems that the old test for node versions 0.6 in 

lib/request/middleware/index.js

breaks more modern apps that run on iojs, since they are now on version 1.6.x

**Proposed fix:**

change line 11 of lib/request/middleware/index.js

    existslib = process.version.split('.')[1] === '6' && require('path') || require('fs');

to 

    existslib =  require('fs');

does it for me

**Comment by paulbjensen** [comment]
Yeah, I think that there was a plan to change that line as Node 0.6 is beyond what we'd look to support today.

Thanks for spotting it. I'll see if we can change it quickly.

**Comment by luksch** [comment]
That would be good, since we use iojs and I now need to write some extra grunt task to let our deployment system work around this. Very annoying....

**Comment by arxpoetica** [comment]
@luksch tangent—but out of curiosity, what are you using SocketStream for?

**Comment by arxpoetica** [comment]
I created a pull request for this. @paulbjensen (or someone) pls. review: https://github.com/socketstream/socketstream/pull/517

**Comment by luksch** [comment]
@arxpoetica

Our application can be found here: https://app.arbvestor.com 

In order to see anything you would need to register @ https://arbvestor.com, which is free. If you are into arbitrage betting this could be of use to you. If you just want to have a peek - well do that then :) 

Note that the production system is still on nodejs, not iojs. iojs is on development environment and we want to switch soon.

**Comment by arxpoetica** [comment]
Cool.

**Comment by arxpoetica** [comment]
I created a pull request for this. @paulbjensen (or someone) pls. review: #517

**Comment by thepian** [comment]
Perhaps add a bit of testing so coverage doesn't suffer?

**Comment by arxpoetica** [comment]
@thepian two things; I'm not fluent enough in the testing environment of SS to add one (sorry!), but also, #517 is not a feature for the `next` branch, but a hotfix on `master`. The idea is to help out @luksch in the short term on `0.3`.

I do plan to get up to speed on the testing environment. If you feel a test is requisite for this hotfix, feel free. Sorry I can't be of more immediate help.

**Comment by thepian** [comment]
Sure nm, we probably merge from next to master anyway. It would be nice if it was merged to next as well though, so people can test out next without loosing hot fixes.

**Comment by arxpoetica** [comment]
I'll cherry pick it in.

**Comment by luksch** [comment]
It would be awesome to get this fix in the npm version soon. Thanks everybody for the effort.

**Comment by thepian** [comment]
@paulbjensen Could we move tasks to 0.3.13 so 0.3.12 can be released soon ? We are getting close to 0.4 anyway so might as well cut down on 0.3 release scope.

**Comment by luksch** [comment]
+1

**Comment by paulbjensen** [comment]
@thepian yes, absolutely fine with me. WRT publishing to npm, what is your handle on npm - so I can add you as an author to be able to do publishing.

**Comment by thepian** [comment]
user on npmjs.com is `thepian`

**Comment by paulbjensen** [comment]
Thanks, I've added you to the npm so you can publish updates.
