### ISSUE TITLE
Make separate team for bots

### ISSUE THREAD

**Issue by thepian** [socketstream/socketstream#522]
Hound CI is a core contributor. Please make a team with less access.

**Comment by arxpoetica** [comment]
I was just thinking about this. What's your reason @thepian? I was definitely noticing that all these bots were creating a lot of noise with all the inline comments on pull requests. I suppose that's a good thing—it forces us to go back and clean up unlinted code. But it also makes it hard to look for non-bot comments in pull requests. Thoughts?

**Comment by thepian** [comment]
Not sure, but we need to be forced to make tests and stick to our linting rules. Personally I don't care about 90% of lint rules as they don't help me read or write the code, but some are a good thing. If there are too many messages we should reduce to a set of rules we can apply and stick to. For code coverage, we have to get to 100%. Refactoring without knowing what is expected and not is impossible. I am making a lot of decisions when refactoring which may or may not be the right ones.

I would prefer to not use houndci, but I think we will not stay on top of our code rules without it.

**Comment by arxpoetica** [comment]
Let me clarify. I care enormously about linting—it's AS GOOD as tests for catching bugs/errors. It also gives code consistency and sanity. I was only questioning the utility of the bots. There are other techniques for linting.

I'm fine with or without bots, just wanted to clarify what I see as the value of linting (absolutely) vs. the value of bots (maybe).

**Comment by thepian** [comment]
If we don't use something like hound, I think a commit trigger or watcher is needed

**Comment by arxpoetica** [comment]
sounds good.

**Comment by thepian** [comment]
Guess nobody cares
