### ISSUE TITLE
how to use the connect bodyParser

### ISSUE THREAD

**Issue by luksch** [socketstream/socketstream#527]
Since 0.3.12 I can't do this anymore:

    ss.http.middleware.prepend( ss.http.connect.bodyParser() );

It was sugegsted in the docs http://socketstream.github.io/socketstream/docs/#/tutorials/http_middleware

Question is, how to get the behavior back?

**Comment by thepian** [comment]
I will have a look at that. Do you know that it is supposed to work with the latest connect?

**Comment by luksch** [comment]
It seems that the body parser is now outside the core of connect.

https://www.npmjs.com/package/body-parser

http://stackoverflow.com/questions/24330014/bodyparser-is-deprecated-express-4

**Comment by thepian** [comment]
That was my assumption, but the deprecation is express not connect. In connect it seems that just a part is deprecated.

**Comment by thepian** [comment]
@kulicuu Did you read anything about this when upgrading Connect ?

**Comment by thepian** [comment]
@luksch Can you check if `connect.bodyParser()` is still there? If not this is really a connect issue, then it is missing documentation. I think prepend still works, but I think tests are missing for that.

**Comment by luksch** [comment]
I fixed our problem by getting rid of the need for body parser altogether. It  was easy, since it was actually a line of code that did not surf any purpose any more. I did not look deeper into this, since I had to go on doing other stuff.
