### ISSUE TITLE
Make 0.4.1 to include existsLib fix

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#532]
We will need to push a 0.4.1 release to resolve the existsLib issue.

**Comment by thepian** [comment]
Indeed. Looking at some other possible fixes to squeeze in.

**Comment by arxpoetica** [comment]
/off-topic, but the whole point of semver is not worrying about minor releases like 0.4.x—do as many as needed to keep things working!

**Comment by thepian** [comment]
Yes I agree, but it still takes me an hour to release making sure nothing is broken. So I don't want to do it every day

**Comment by thepian** [comment]
On a tangentially related note I've noticed that engine-io client is loaded as a library. Shouldn't it be loaded as a CommonJS module ? Perhaps @kulicuu can comment.
