### ISSUE TITLE
When initiating new app it is 0.3.12 and not 0.4.2. Why?

### ISSUE THREAD

**Issue by ilyador** [socketstream/socketstream#538]
When doing `socketstream new <name>` I get a 0.3.12 app and the SS in package.json is also 0.3.12. Why not 0.4.2?

**Comment by paulbjensen** [comment]
This is a bug, we'll fix it shortly.

On 8 May 2015 at 09:36, Ilya Dorman <notifications@github.com> wrote:

> When doing socketstream new <name> I get a 0.3.12 app and the SS in
> package.json is also 0.3.12. Why not 0.4.2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketstream/socketstream/issues/538>.
>



-- 
Paul Jensen
07914 171 345

**Comment by thepian** [comment]
Is it hardcoded? It should certainly be read from package.json

**Comment by paulbjensen** [comment]
It is - https://github.com/socketstream/socketstream/blob/master/lib/cli/generate.js#L183

We can change that so it reads it from the package.json file.

**Comment by ilyador** [comment]
Where can I find a 0.4 app example?

**Comment by kulicuu** [comment]
https://github.com/socketstream/ss-examples/tree/master/react-and-coffeescript

I didn't use the CLI script -- don't typically.  Just built the relevant file structure.

**Comment by thepian** [comment]
@ilyador 0.4 should work like 0.3 with only one or two edge cases difference
