### ISSUE TITLE
0.4.2: Client Code Bundling Problems

### ISSUE THREAD

**Issue by hulmgulm** [socketstream/socketstream#542]
Hi,

after switching to 0.4.2 we have the following two issues with client code bundling:

1. our app now bundles after each startup as it is not able to find the previously packed assets although they are still there.

2. bundeled app cannot find entry.js
We've configured our app to load the client code from:
code: ['libs', 'app', 'copiedFromServer'],
In client/code/app we have an entry.js. Now the bundelred app complains:
Uncaught Error: Cannot find module '/code/app/entry' within '/'
When I look into the bundeled js it has an
require.define("/app/entry"

Running the app unpacked works fine.

Thank you,
   Andreas

**Comment by arxpoetica** [comment]
@thepian any thoughts on this? ^

**Comment by thepian** [comment]
My thoughts are 'crap' :(

I wasn't able to write a unit test for the recognising of existing bundled files, it should be a trivial change but clearly an annoying bug.

entry.js and index.js should both work as there are unit tests for them. Something must be missing.

Regarding 2 is the problem with the bundled version ?

**Comment by kulicuu** [comment]
I'm getting problems also with the bundling.

**Comment by kulicuu** [comment]
The `client.id` injected into /lib/client/http.js is bad.  I may have a fix tomorrow.

**Comment by kulicuu** [comment]
Even more unpredictable behaviour from the bundler upon casual console based testing today.  All indications are I should step back from the console based testing as it will not be time efficient--long term better to focus on the unit testing and concomitant improving of the understanding of the higher level structure of the system -- in this case the client module. 
It's been so long since I even ran the unit tests we have -- how is this done ?  I know it's Mocha.  Could we put a readme.md in the /test folder documenting testing structure, strategy, invocation etc ?  Would be nice.

**Comment by paulbjensen** [comment]
run <code>npm test</code> on the command line.

**Comment by paulbjensen** [comment]
Once I get my chapter submitted and another book meeting done, this item is next on my todo list.

**Comment by kulicuu** [comment]
ah thanks.

**Comment by thepian** [comment]
Isn't that something mocha has documented?

**Comment by thepian** [comment]
@hulmgulm If you have any chance can you test #553 it should solve your issue point two. I think the only left is reusing existing asset files.

**Comment by kulicuu** [comment]
@thepian I know mocha stuff, but documenting it in a readme.md eg:
https://github.com/kulicuu/britvic/tree/master/mocha

Like it's a good idea to be able to run different suites at different levels checking out individual modules or sometimes working relations between them.

**Comment by thepian** [comment]
Got ya

**Comment by thepian** [comment]
Regarding point 1, I'm still trying to write a test that covers this fully.

**Comment by thepian** [comment]
Point 1 will be fixed in 0.4.4, others are on master and will be in 0.4.3
