### ISSUE TITLE
superfluous argument in invocation

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#544]
[here](https://github.com/socketstream/socketstream/blob/master/lib/socketstream.js#L133) in the method invocation there is a second argument `responders` which is not in the method [definition](https://github.com/socketstream/socketstream/blob/master/lib/websocket/index.js#L14), and I looked back some months it looks like it hasn't been used in quite awhile if ever.
Just leaving this issue here as a reminder to delete the second arg in the invocation, or if someone objects  to call it up.

**Comment by kulicuu** [comment]
I should mention also, it's confusing when the argument name in the invocation is different from the argument name in the definition.  In this case it's `api` in the invocation and `ss` in the definition.  It should probably be `api` in the definition as well.

**Comment by arxpoetica** [comment]
Looks good.
