### ISSUE TITLE
new dependency request : immutable

### ISSUE THREAD

**Issue by kulicuu** [socketstream/socketstream#547]
https://github.com/facebook/immutable-js

On both client and server sides.

**Comment by arxpoetica** [comment]
Interesting...

**Comment by thepian** [comment]
To me that is squarely in the examples / how-to bundle with bower/jspm/browserify category. I will add a documentation flag, sound good ?

**Comment by kulicuu** [comment]
@thepian  I'm not sure what you mean about examples or bundling.

**Comment by kulicuu** [comment]
[a bit more about this]
For a long time I'd been deferring learning functional programming properly.   Or declarative vs imperative.

I've been reading this blog a lot 
[http://bartoszmilewski.com](http://bartoszmilewski.com]

I've also been immersed in a lot of reengineering projects, in particular really a long term thing with a C++ codebase.  

I considered maybe SocketStream might benefit moving forward from implemention leveraging these tools.  Clearly I can create branch of my fork devoted to it and start there -- but also wanted to hear from you about it.  Also, if the dependency were there on the master branch, it would be possible to (feet wet) start using the API in a small way experimentally, before making really more drastic changes.

**Comment by paulbjensen** [comment]
Are there parts of SocketStream's code where this should be used? It would be good to see an example of how using Immutable.js would improve it.

**Comment by kulicuu** [comment]
I don't think there would be any improvement implementation-wise.  Structure and organisation of the code might be improved substantially; better maintainability.  Just a hunch based on current research.  
[from](http://bartoszmilewski.com/2015/05/14/using-monads-in-c-to-solve-constraints-2-the-state-monad/)
>I am sometimes asked by C++ programmers to give an example of a problem that can’t be solved without monads. This is the wrong kind of question — it’s like asking if there is a problem that can’t be solved without for loops. Obviously, if your language supports a goto, you can live without for loops. What monads (and for loops) can do for you is to help you structure your code. The use of loops and if statements lets you convert spaghetti code into structured code. Similarly, the use of monads lets you convert imperative code into declarative code. These are the kind of transformations that make code easier to write, understand, maintain, and generalize.

**Comment by kulicuu** [comment]
also see:
[immutable-js#the-case-for-immutability](https://github.com/facebook/immutable-js#the-case-for-immutability)

I don't mean to distract from more prosaic near-term goals.  I've really been hit hard with some reengineering problems recently, and high level issues of how to develop complex software systems is very much on my mind these days.  Could say I've adopted a paradigm of continuous reengineering. 

I'm looking at how SocketStream works in some detail, and thinking about ways that it could work better.  Especially given newer tools and techniques.

**Comment by kulicuu** [comment]
For now I'll branch on my fork and play around with it.  I will be looking for examples that I could share here, as you've indicated.

**Comment by arxpoetica** [comment]
For the record, you can maintain immutable code *without* an added library: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by kulicuu** [comment]
_no stress_ :)

**Comment by paulbjensen** [comment]
@kulicuu ok to close the issue?

**Comment by paulbjensen** [comment]
Pressed wrong button.
