### ISSUE TITLE
Code Coverage is reporting different numbers on different runs

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#551]
Hi,

I've just noticed that the code coverage reported a drop when it shouldn't have reported any change in the code coverage. I'm going to investigate and see what's going on.

**Comment by paulbjensen** [comment]
I've tracked this by running <code>npm run cover-test</code>, and these results vary:

![screen shot 2015-05-24 at 16 24 15](https://cloud.githubusercontent.com/assets/3840/7788415/abc91452-0231-11e5-854c-5a643e574d8c.png)

and this

![screen shot 2015-05-24 at 16 24 35](https://cloud.githubusercontent.com/assets/3840/7788416/b2d10a70-0231-11e5-9dd1-a91c223e9dad.png)

You can see that the lib/client and lib/client/bundler's coverage stats change between runs, so I will look into the code and tests and see why they're varying.

**Comment by thepian** [comment]
Is it because they sometimes fail during coverage tests?

**Comment by paulbjensen** [comment]
Not always - I've just been running <code>npm run cover-test</code> a couple of times, current coverage results reports 76.77%, but on one case where everything passed, it returned 76.83%. I'll isolate where the variance is occurring.

**Comment by thepian** [comment]
I'm attempting to extract a fixtures module with fixtures and utilities to reset and cleanup the project fixture before/after each test. Hopefully it will make test runs more stable.

**Comment by thepian** [comment]
Could it have to do with live-reload kicking in and executing more code?

**Comment by thepian** [comment]
I think it was. When I run it with the pack-improvements branch the coverage numbers remain the same

**Comment by thepian** [comment]
fixed in master
