### ISSUE TITLE
Allow for different MIME types in dev mode.

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#556]
See this thread: https://groups.google.com/forum/#!searchin/socketstream/mime/socketstream/PcKCoFcaSW0/pu_IrxHKsdYJ

It doesn't appear that we can serve different MIME types in development mode.

**Comment by thepian** [comment]
Wouldn't we want to move away from implementing a general purpose app server?

I would expect that it is trivial to prepend a middleware which will serve special mime types. In production you should have the static server handle this anyway I would think.

I'm not against the improvement, just think it is a distraction beyond documenting how to write your own static serving middleware for DEV time. There must be 100+ blog posts that explain how to do this with Connect/Express.

**Comment by arxpoetica** [comment]
@thepian I don't disagree—however—currently it's not possible to hook into the middleware for the MIME type in dev mode—unless I'm missing something.

**Comment by thepian** [comment]
We now have an Express 4 example.

**Comment by arxpoetica** [comment]
:+1:
