### ISSUE TITLE
Remove console log statement on cookie secret in engine.io

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#559]
I see a line like "secret in engine.io feK4li1aek8koe7JeiC3shai7ahy7uduch5ahY7n" when running the latest SS. It seems like a console logging statement that has been left somewhere in the codebase. I will find it and strip it out.

**Comment by kulicuu** [comment]
`etstream/lib $ grep -R "secret in engine.io"
websocket/transports/engineio/index.js:  c('secret in engine.io', secret);`

my bad.  I would need to pull latest and some associated tasks before PR for it.

**Comment by kulicuu** [comment]
fixed at
https://github.com/socketstream/socketstream/commit/495229c25a72de0bf30cfde1c2e2fe6991dd2f9b
