### ISSUE TITLE
multiple angularjs clients cannot work

### ISSUE THREAD

**Issue by EricCat** [socketstream/socketstream#560]
ref this [doc](http://socketstream.github.io/socketstream/docs/#/tutorials/defining_multiple_clients)
I defined two angular client app & app_test
```
ss.client.define('app', {
  view: 'app.jade',
  css:  ['libs', 'app.css'],
  code: ['libs', 'app'],
  tmpl: ['app']
});
```
```
ss.client.define('app_test', {
  view: 'app_test.jade',
  css:  ['libs_test', 'app_test.css'],
  code: ['libs_test',  'app_test'],
  tmpl: ['app_test']
});
```
[entry.js](https://gist.github.com/EricCat/516a9f7a5e53bd5911ae)

the ``app`` module works fine, but ``app_test`` can't work with error : ``angular is not defined``.
Any ideas for this issue?

**Comment by thepian** [comment]
I assume you put angular in libs. Did you make a libs_test as a copy of libs? why?

The documentation on libs explains that it's a special case where the file is loaded raw, not as a module. Angular isn't there as you didn't do a require for it, and it will not be a global variable if you do.

**Comment by thepian** [comment]
@EricCat Can you confirm this so I can close the issue?

**Comment by thepian** [comment]
No feedback on this. Working as documented it seems.
