### ISSUE TITLE
ss-console error with ss.log

### ISSUE THREAD

**Issue by havoc74** [socketstream/socketstream#561]
When using ss-console, an error is thrown at start up:

.../node_modules/ss-console/lib/server.js:26
    ss.log("i".green, "Console Server running on port " + port);

Simply changing "ss" to "console" fixes the issue. I know you're all still working on things, so take this as just a head's up. Great work by the way, thanks!

**Comment by paulbjensen** [comment]
Thanks for spotting the issue and putting it on Github. Give me a couple of minutes and I'll fix it.

**Comment by havoc74** [comment]
Excellent, thank you!

**Comment by paulbjensen** [comment]
Hi, I've pushed a fix up (https://github.com/socketstream/ss-console/pull/8), and published it with ss-console 0.1.4 on NPM. I'll close it but if you have any further issues please reopen and let me know.

**Comment by havoc74** [comment]
Thank you Paul :)

**Comment by havoc74** [comment]
I do verify that it is working now without error after an npm update ss-console, thanks again!

**Comment by thepian** [comment]
@havoc74 Since you are a user of ss-console I'd like your opinion on how to best evolve the console for SocketStream 0.5

Do you have special wishes or any low hanging fruits that could be added/changed ?
