### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#562]
Looks like we're outdated on quite a few. Just making note to check them.

![image](https://cloud.githubusercontent.com/assets/111424/8697641/b89587c2-2ac4-11e5-98a7-4121eeee5c7b.png)

This ticket came about because I was having problems with `chokidar`, which I had to update to the latest version in my local copy of socketstream:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/.../socketstream/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /Users/.../socketstream/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup
```

Quite a few dependencies are out of date. We should do an update and make sure all systems are go.

**Comment by paulbjensen** [comment]
Yes, definitely, but also worth checking them with production apps as well before merging into master and publishing on npm.

**Comment by arxpoetica** [comment]
Good idea.
