### ISSUE TITLE
0.4.3: Asset packing does not work.

### ISSUE THREAD

**Issue by hulmgulm** [socketstream/socketstream#564]
I've created a new app with SS 0.4.3 with the command "node socketstream new myapp".

When running this app with "SS_ENV=production", it is not working anymore. I get the following error in my browsers console:

Error: Cannot find module '/code/app/entry' within '/'

When I check the generated JS file in the assets directory, I see a

require.define("code/app/entry" ....

For me it looks like the asset packing is broken.

**Comment by thepian** [comment]
We have unit tests covering this. My guess is that the new app skeleton needs to be updated somehow.

**Comment by paulbjensen** [comment]
It's to do with the use of * to select all directories on Windows. Windows does not like * for some reason.

**Comment by paulbjensen** [comment]
Sorry, wrong issue.

**Comment by thepian** [comment]
@hulmgulm can you run the test suite on Windows ?
I'm very disinclined to set up a dev environment on windows, so I would have to rely on others telling me what fails. We have mostly removed any assumptions about path separators, but it could be that we have some issue with assuming a Unix OS somewhere.

**Comment by thepian** [comment]
fixed on master, new project now works on Windows
