### ISSUE TITLE
Windows template * not supported, rework implementation

### ISSUE THREAD

**Issue by hulmgulm** [socketstream/socketstream#565]
I've created a new app with SS 0.4.3 with the command "node socketstream new myapp".

During start of this app, I see the following error:
! Error: C:\test\client\templates\* directory not found

Inside the templates directory there is a file called chat\message.html

The browser reports the following error:
TypeError: ss.tmpl['chat-message'] is undefined

It looks like the template handling is not working as expected.

**Comment by paulbjensen** [comment]
I've been able to replicate the error on Windows. Will investigate and fix.

**Comment by paulbjensen** [comment]
The way I've managed to fix this is by changing the app.js file on line 11 to this:

    tmp: 'chat'

Using '*' as a folder wildcard on Windows does not work. It we swap out '*' with the name of the 1st and only folder (chat), then the app works.

Changing this in the app generator would fix generating new apps with the demo app code, but not apps with a minimal install.

I'll keep searching for a way to support folder wildcard on Windows.

**Comment by thepian** [comment]
does the globe package work on Windows ? It is usually preferable to rolling your own

**Comment by ChristianEnchelmaier** [comment]
Same issue here, will there be a fix shortly or is there any workaround?

` ! Error: C:\prj\Dashku\client\templates\* directory not found`

**Comment by paulbjensen** [comment]
Hi Christian,

My workaround for the SS chat app was to simply pass the folder/file name <code>chat</code> in, rather than use the <code>*</code> character to select everything.

For Dashku, try changing the <code>tmpl:</code> on line 37 to this:

    tmpl: ['account','app','dashboard','dashboardView','docs','homepage','widget','alert.jade','changePasswordModal.jade','inputFieldError.jade','loginModal.jade','signupModal.jade']

If this works on Windows, please let me know, or better, submit a Pull request to Dashku and I'll review and merge it in.

**Comment by ChristianEnchelmaier** [comment]
Hi Paul,

thanks for the quick reply. The fix worked directly - i've sent u a pull request.

**Comment by paulbjensen** [comment]
Thanks, merged it in.

**Comment by thepian** [comment]
Perhaps we should try using multimatch module.

**Comment by paulbjensen** [comment]
@thepian Yes, that could work. I have a laptop with Windows on it so I can test it there.

**Comment by thepian** [comment]
There is now a feature branch using the glob module, if anyone can test on Windows for possible fix that would be great.
