### ISSUE TITLE
Bug: new generated app not loading clients

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#572]
I tried to generate a new SS app with <code>socketstream new</code>, installed dependencies, npm linked to the version on master, and came across this issue:

<img width="986" alt="screen shot 2015-08-26 at 23 35 12" src="https://cloud.githubusercontent.com/assets/3840/9506934/54e7c19c-4c4b-11e5-8b09-15839ff48e43.png">

It seems as though the client is not being loaded, even though it should be based on the app.js file of the default app telling it to.

**Comment by paulbjensen** [comment]
I've dug a little into this so far (FYI I'm running on Mac OS X Mavericks and io.js 3.1.0)

The lib/client/index.js file is calling lib/client/http.js with a <code>clients</code> object, which stores the clients. At the time of initialisation, the clients object is empty.

When we call the ss.client.define function in the app, the client is added to the <code>clients</code> object in lib/client/index.js, but http.js has the empty object that was passed into it. Basically we need a way to share the clients object state between both files without message passing.

**Comment by paulbjensen** [comment]
This seems to be happening even on 0.4.3 (not just master branch).

**Comment by paulbjensen** [comment]
Some further testing, it looks like an issue with iojs and not Node.js 0.12. Going to do some more testing to verify.

**Comment by thepian** [comment]
Yes, I've noticed. Had trouble on one machine. I would like to fix it, but also wonder about the userbase for iojs

**Comment by thepian** [comment]
iojs passing for latests master, can you check if the issue is resolved?

**Comment by paulbjensen** [comment]
Will do in 2 hours' time (at work atm).

**Comment by thepian** [comment]
@paulbjensen any news?

**Comment by paulbjensen** [comment]
Sorry, totally lost track of this. Gimme 10 mins.

**Comment by paulbjensen** [comment]
Latest version of master works, thanks. Will close.

I realised that if the version of socketstream points to 0.4.3 but the repo is linked to master, it will cause errors, and if the generator points to master but app loads 0.4.3, then another error occurs.

Basically, always check that the app generator and the module loaded by the app are the same.
