### ISSUE TITLE
Bundling client files outside of the client folder

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#575]
Is it possible to bundle files from outside the client folder? Scenario. Want to include optional/additional files based on an installed template. (Think about how WordPress works if you're wondering what I mean.)

Example:

```js
var clientDefinition = {
	view: 'app.jade',
	css: ['app.styl'],
	code: ['app'],
	tmpl: ['*']
};
var js = 'node_modules/some-example-template-code/code';
if (fs.statSync(js).isDirectory()) {
	clientDefinition.code.push('../../' + js);
}
```

Obviously, my example isn't working, it's only meant to illustrate. Can anyone think of a working way to do something *like* this? In essence, it would be awesome to just `require` something and bundle it that way, but that might be a whole new feature to build out. Is there another working way though?

**Comment by thepian** [comment]
Yes that is already supported in 0.4

You can use relative paths in code

  ss.client.define('main', {
    view: 'app.html',
    css:  ['libs/reset.css', 'app.css'],
    code: ['libs/jquery.min.js', '../node_modules/somthing/code', 'app'],
    tmpl: '*'
  });

Relative paths are based on the client directory. I wish we had it documented.

**Comment by arxpoetica** [comment]
Excellent, I'll give it a try.

**Comment by arxpoetica** [comment]
Hmm...not working. With the following dependency:

```code: [..., '../node_modules/Template/code'```

I get the following error:

```! Error: /Users/[user]/Documents/workspace/[project]/client/node_modules/Template/code directory not found```

Seeing that `/client/` directory still in that path...so if I try adding an extra `../` I get the following:

```Couldn't serve client main, issue=1441074633914 
ENOENT, no such file or directory '/Users/[user]/Documents/workspace/[project]/client/Template/code/template.js'
client=N131alA3
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
[...etc...]
more:
{"bundle":"js","file":"/Template/code/template.js","ext":"js"}
```

Clues? I have a local (up to date) copy of SocketStream. If you can point me in the right direction, I can try and debug myself.

**Comment by thepian** [comment]
I have only tried it with using alternate directories within the client directory, but in principle it should work.
It is still an open issue to support npm/bower modules installed anywhere in your project.

client/bundler/default.test.js:120 tests relative paths within the client dir.

ss.bundler.sourcePaths(paths) determines where source roots are located. If something doesn't work this is the function that needs fixing.

Your issue seems to be in client/bundler/index.js:278

**Comment by arxpoetica** [comment]
Okay. I'll look into it and possibly do a PR. :snowman:

**Comment by arxpoetica** [comment]
So I'm still following the papertrail, but I was surprised to figure out that the path for finding assets is parsed from `request.url` at `socketstream/lib/client/serve/dev.js:42-46` (as part of `serveJS`). In other words, it's getting parsed off the query from this string: `/assets/main/VJeVNUJp.js?_=[MyTemplate]/code/template.js`

What's the reason for doing this? Seems a bit backward.

**Comment by thepian** [comment]
not sure what the question is. Are you referring to the URL scheme during development?

1) It mimics the location in production to keep them similar and make CSS work the same
2) It contains the client name, ID and type to use the correct bundler
3) It contains the path relative to the client directory to support files outside the usual locations
4) It contains a query to bust the cache during development
5) The parsing of the query part should be done by the bundler, but hasn't been implemented yet

**Comment by arxpoetica** [comment]
So if no. 3 is true, then it appears to be broken...but I'm still digging into that... ;)

Not sure what you mean in no. 5. Are you saying that the query parsing is done in another way, but should really be handled by the bundler?

**Comment by arxpoetica** [comment]
Okay, a little further down the rabbit hole. It doesn't look like the final source of the problem, but [line 631 in the bundler index file](https://github.com/socketstream/socketstream/blob/5af594a3f80af55a30fb15be9a72a1c80e15ab41/lib/client/bundler/index.js#L631) is trying to do a `path.join` with an incomplete path part. Specifically it looks like the `rel` variable is not a relative path.

So let's say I feed the client definition a path like `../../node_modules/Template/code/template.js`, the `rel` variable somehow comes through as just `/Tribe-Kupuna/code/template.js'. In other words:

    path.join(ss.root,options.dirs.client,rel)

transliterated looks like:

    path.join('/Users/[user]/Documents/workspace/[project]','/client','/Template/code/template.js')

So...what happened to `../../node_modules'? A little confusing. But it looks like the `rel` variable is coming from `request.url` at `socketstream/lib/client/serve/dev.js:42-46` as I mentioned above. So maybe that's just a bad way of parsing the variable? Hope this is helping and not just confusing. :P

**Comment by thepian** [comment]
3) It does work for file within the client directory, so you can load a JS file from outside client/code, but I don't expect it to work with `../elsewhere` paths; Although it should. (still an open issue)

The idea was to support any asset path to be passed in the URL using the _ parameter. It would be a path relative to the client directory. The file in question would also have that as the logical path in browser source mapping (perhaps relative to project root would be even better, but that is quite a rewrite).

The idea was to leave the interpretation of the path to the bundler, but it is still being done in dev.js as it was before.

The bundler determines the list of client assets and links them in the HTML view. They are loaded by the browser and the bundler should resolve the paths as well.

**Comment by thepian** [comment]
I've starting fixing this. The first part of pulling in stuff outside the client directory is an easy fix already on the feature branch. Second part is making require work for anything in the project directory. This means that the path in the bundle should be /client/code/abc.js not /code/abc.js

**Comment by arxpoetica** [comment]
If I'm understanding you correctly, that would be a breaking change? I'm okay with that, but it should be documented.

**Comment by thepian** [comment]
nope, everything working as before. It is all internal to wrapCode and what path modules are registered under which is unspecified. Otherwise it would be for 0.5

**Comment by arxpoetica** [comment]
:+1:

**Comment by thepian** [comment]
Lot's of little internal changes though. Started with 40 unit tests to fix, down to 6

**Comment by thepian** [comment]
The feature branch should now allow any client assets to be referenced inside the project using relative paths with the client folder as the starting point

**Comment by arxpoetica** [comment]
Yow. It makes sense though. When I tried to debug a few weeks ago, like I said, the path variable was all over the place. It made me wonder if there was a cleaner way of keeping track of and using paths.

**Comment by thepian** [comment]
We should change the new app template to fetch jquery from node_modules and have jquery be an npm dependency.

**Comment by thepian** [comment]
Perhaps I should change the templateEngine.use path param to be relative to the client. Right now it's relative to the project.

**Comment by thepian** [comment]
in master
