### ISSUE TITLE
Get SocketStream working w/ Node v 4.0.0

### ISSUE THREAD

**Issue by arxpoetica** [socketstream/socketstream#576]
Now that io.js and node.js are streamlined, I tried running SocketStream against v4. `segmentation fault`! Ope! This happened when I created one single file and *only* did the following:

```
var ss = require('socketstream');
```

(Nothing else.)

**Comment by paulbjensen** [comment]
Hi Robert, segfaults tend to occur if you install an npm module with compiled dependencies using one version of Node, then try to run it after switching to another version of Node. 

I'd like to suggest trying to re-install SocketStream on Node v4.0.0, and then seeing if you still get that error.

**Comment by paulbjensen** [comment]
Hi Robert,

I can confirm that Socketstream works on v4.0.0. 

I did the following:

```
nvm install v4.0.0
npm install -g socketstream
socketstream new another-app
cd another-app
npm install
npm start
```

Please confirm it works for yours well.

**Comment by arxpoetica** [comment]
Hmm. Maybe I've done something bad on my installation w/ `nvm`. I've done the first two commands above. After running the third, however (`socketstream new another-app`), I get:

```bash
[1]    8163 segmentation fault  socketstream new another-app
```

I'll keep digging and see what's going on.

**Comment by paulbjensen** [comment]
Interesting, what's your OS and version? (mine was Mac OS X Yosemite 10.10.5)

**Comment by arxpoetica** [comment]
Same, but 10.10.4.

**Comment by arxpoetica** [comment]
For what it's worth, when I do `nvm use 0.12.7`, it starts working again. I'm thinking this must (somehow) be a system thing, and not have anything to do w/ SocketStream. But where to begin... :wink:

**Comment by paulbjensen** [comment]
I'd suggest checking where the socketstream binary points to with <code>which socketstream</code>

**Comment by arxpoetica** [comment]
Okay. So I got my app running. Turned out I needed to update my npm dependencies, oops: http://stackoverflow.com/a/32289269/209803 Makes perfect sense.

However, still not clear on why a global build of socketstream would segfault. Here's the `which`:

```bash
$ which socketstream
/Users/[user]/.nvm/versions/node/v4.0.0/bin/socketstream
```

I'll keep working on that, and close the issue when I figure it out. I'm sure it's similar to the problem I had in my actual app.

**Comment by arxpoetica** [comment]
Oh weird. Now my global socketstream is working. Strange. Maybe updating my local build tricked the system. I'm not sure what I did, but we're good. Closing.

**Comment by thepian** [comment]
I run SocketStream 0.5 on the latest NodeJS, all seems fine. I would actually consider making SocketStream 1.0 require NodeJS 4

**Comment by arxpoetica** [comment]
agree. will solve a lot of problems not supporting backward compatibility.
