### ISSUE TITLE
RPC not loading on tests

### ISSUE THREAD

**Issue by cuckoopt** [socketstream/socketstream#588]
Hi,

With the latest version of sockectstream, the rpc's are not loading on my app, was there any major change in the way these are loaded?
On the tests header i have the usual `require("socketstream").start()` which is at `test/server/rpcs.test.js`... For the frontend the rpc's load perfectly, is there anything that I need to do differently on this version?
This is my current folder structure:
```bash
.
├── app.js
├── gulpfile.js
├── package.json
├── client
│   ├── code
│   ├── css
│   ├── modules
│   └── views
├── node_modules
├── server
│   ├── jobs
│   ├── middleware
│   ├── models
│   └── rpc
└── test
    ├── client
    │   ├── modules
    │   └── views
    ├── mocha.opts
    ├── protractor.conf.js
    └── server
        ├── jobs
        ├── models
        ├── models.test.js
        ├── rpcs
        └── rpcs.test.js
```

Tasks

- [x] Add sample transporter tests
- [x] Document transporter tests

**Comment by thepian** [comment]
Hi there, are you talking about 0.5.0 ? It is an unstable release for testing only. Thanks for reporting.

Indeed much is changing. calling start without an http server is now supported to facilitate gulp integration and running pack-all as a task. https://github.com/socketstream/ss-examples/blob/master/express-4-and-js/app.js

It means that transporter tests will have to be supported in a different way. There is already a task for that. If you can point me to an example test that doesn't pass anywhere, I'll be happy to fix the issue.

**Comment by thepian** [comment]
You might be able to make your test work by calling ss.load() instead of ss.start(), hmm probably not will have to look into this

**Comment by thepian** [comment]
@cuckoopt Could you try out your tests with this: https://github.com/socketstream/socketstream/pull/590 ?

**Comment by cuckoopt** [comment]
I was talking about the 0.4.4, I tried to run the tests with that line both with 0.4.4 and 0.5.0 and in the 2 of them I get
```javascript
! task failed { [Error: task "test-socketstream" is not defined]
  missingTask: 'test-socketstream',
  taskList: 
   [ 'start-server',
     'load-api',
     'load-socketstream',
     'serve',
     'live-assets',
     'live-reload',
     'stop-server',
     'default',
     'pack-all',
     'pack-if-needed',
     'pack-prepare' ] }
```

**Comment by cuckoopt** [comment]
@thepian Sorry, I didn't test with that branch, I tested with it (without the `done` callback, outside of the describes) and it seems to be working fine :+1: 

btw (offtopic) the newer versions will bring the updated deps? it's a bummer to not be using node 4 to installing this... :stuck_out_tongue:

**Comment by thepian** [comment]
Sorry, I'm unable to keep up with all software details. Node 4 completely missed my radar. We can add Node 4 to the platforms tested. Does that bring Promises and other ES 2015 goodies?

With 0.5.0 we are moving away from bundling big dependencies in SocketStream. This means your project is checked for stuff like Jade and Engine.io and you can use the version you are happy with as-long-as it remains API compatible.

I want to shrink SocketStream to a small bundle of glue that you can stick big pieces on and it will make things work together.

**Comment by arxpoetica** [comment]
FYI, Node 4 is the merger of io.js back into the main Node branch (io is no longer a thing). And yes, it includes lots of new goodies as well as more frequent updates (on Semver). We should *definitely* add Node 4 to the test suite. Actually, it's going to be a more rapid moving target. We're already on `4.2.1`.
