### ISSUE TITLE
Relative path for serving assets and code

### ISSUE THREAD

**Issue by gbraad** [socketstream/socketstream#599]
At the moment I am using a test application to see if streamsocket is a fit for our purpose. We are deploying the application behind a small PaaS and all requests are being proxied as path-based. Tjis is currently by-design. This means that applications would have to be served using a proxy-rewriting... or be served using a relative path option. I was wondering if SS provides a relative path option... in my search in the code I have not found this. If not, where could I enable this easily?

**Comment by thepian** [comment]
The HTTP side is intended to be essentially static in production. You generate bundles for HTML,CSS and JS. On demand JS is currently only supported on the server, but will be static as well in 0.6 or 0.8

So in production the only thing to proxy is the websocket connection and fallback support from SockJS/Engine.io

What I'm essentially saying is that there is nothing in SocketStream itself that needs to be handled in production. You just need to serve the static and assets directories from your HAProxy/Nginx frontend and proxy to the SocketStream server for the connection.

There is no particular support for configuring the path for where the fallback XHRs go. You'd have to refer to the transport documentation for that.

**Comment by thepian** [comment]
Hmm, did you just mean the `/assets/` URL? Can't you just monkey patch the bundler or make a new one? the function to patch is htmlTags

**Comment by thepian** [comment]
@gbraad Is the issue solved for you?

**Comment by thepian** [comment]
btw why would proxy rewrite be an issue, it's pretty standard

**Comment by gbraad** [comment]
I haven't been able to look into this further in recent time. The proxy rewrite would not be a problem, but having the flexibility from within socketstream to define the paths would be appreciated, although not essential. It would be considered advanced functionality. Note: the proxy-ing in question is really lightweight and does not involve nginx as it is done on a simple ARM-based device using only Node.js

**Comment by thepian** [comment]
As mentioned above you can already do that with the CDN configuration for assets. It isn't clear to me what you are trying to achieve though as all HTTP traffic in production should be static assets or SockJS/Engineio traffic.

If there is no clear requirement or issue I will have to close this
