### ISSUE TITLE
Transport for "undefined" must be a function

### ISSUE THREAD

**Issue by jerrygzy** [socketstream/socketstream#600]
Transport for "undefined" must be a function(ss, emitter, config) default: undefined
! task failed [TypeError: Cannot read property 'listen' of undefined]

I am new to SS, what is the problem here?

here is my environment
 node v4.2.2
 npm  v2.14.7

{
  "name": "uSee",
  "description": "An awesome real time application",
  "version": "0.0.1",
  "author": "Me <me@mydomain.com>",
  "private": true,
  "engines": { "node": ">= 0.10.0" },
  "dependencies": {
    "normalize.css": "3.0.x",
    "es6-shim": "0.33.x",
    "socketstream": "0.5.x",
    "socketstream-cookie-session": "0.5.x",
    "engine.io": "1.5.2",
    "engine.io-client": "1.5.2",
    "ss-hogan": "0.1.x"
  },
  "scripts":{
    "start":"node app.js"
  }
}

**Comment by thepian** [comment]
Did you create the app with `socket stream new uSee` or did you follow the documentation?

Does you app.js look like: https://github.com/socketstream/ss-examples/blob/master/legacy-app/app.js ?

0.5.1 is an unstable release so it may have issues will ship 0.5.2 in the coming week

**Comment by thepian** [comment]
@jerrygzy The newly released 0.5.2 should work for you
