### ISSUE TITLE
Website URL/certificate woes...

### ISSUE THREAD

**Issue by pygy** [socketstream/socketstream#615]
Hello fellows, long time no see, glad to see the project is still kicking.

the Github "homepage" field points to https://socketstream.com whose certificate has expired. The HTTP URL is redirected to HTTPS.

The certificate for the .org is registered for *.anaphenix.com, but at least the HTTP version is served.

Edit: looking deeper into the cert error messages, they are not self-signed as I initially though. Post updated accordingly.

**Comment by paulbjensen** [comment]
Hi,

I've started the process of reissuing the certificate for it, we will see how it goes.

**Comment by paulbjensen** [comment]
The SSL cert for socketstream.com has been updated

**Comment by pygy** [comment]
👍 
Works from here now.
