### ISSUE TITLE
Grab bag of issues

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#617]
I'm finishing up on the book at Manning, and I will have some more time to work on SS.

Looking at the repo, it looks like there are a couple of things to sort out:

- Issues on the repo (getting any bugs fixed there)
- Dependencies needing updating (the version of uglifyJS that SS is using has a security vulnerability)
- Getting code coverage up (it's improved massively given there weren't any tests to begin with)
- Maybe removing some of the files in the repo
- Making sure that the develop branch can be merged into master (currently has merge conflicts)

I'm opening this one up as a tracker. I will file PRs when this is done.

**Comment by paulbjensen** [comment]
I'd like to propose that we simplify the branching strategy.

At the moment there are 2 versions of SocketStream being worked on - 0.5 (unstable) in the develop branch and 0.4 (stable) in the master branch. I'd like to propose getting the 0.5 branch stable first, then getting it merged into master and dealing with the merge conflicts that currently exist there.

The goal is so that we don't have to duplicate code fixes across multiple versions of SocketStream.

**Comment by arxpoetica** [comment]
Agreed. Full steam ahead.

**Comment by paulbjensen** [comment]
@thepian thoughts?

**Comment by paulbjensen** [comment]
Does anyone object if I go ahead and do this?

**Comment by arxpoetica** [comment]
@paulbjensen no objections. To be honest, I've moved on from the glory days of SocketStream--been using Svelte and Sapper for my latest projects. It was a great ride though! Definitely make any changes you think appropriate.

**Comment by paulbjensen** [comment]
Cool. I will go and do it.

**Comment by paulbjensen** [comment]
Closing as I haven't work on this and I won't be able to commit any time to it.
